- src/components/form/Form.js
I'm currently working on adding Axiom to a new project which is using Webpack 2. During the setup of the configuration I came across an issue which seems to be related to Webpack 2 and the sass-loader plugin: It can't handle empty .scss files.
As the `Form.scss` is empty anyways I don't see a need to keep this file.
> fix(Form): Removed empty Form.scss to prevent sass-loader from failing with Webpack2

- src/components/table/Table.scss
- src/components/table/TableCell.js
- src/components/table/TableCell.test.js
- src/components/table/__snapshots__/TableCell.test.js.snap
- src/components/table/example/grow.js
- src/components/table/example/index.js
This change is required to meet a design requirement on an axiom table. As far as I'm aware this is the way to achieve an expanded column in a table, but open to other suggestions if anyone has them. Thanks!
> feat(TableCell): add expand prop so table columns can be stretched

- src/components/context/Context.css
The above example is a screenshot from IE11 which does not support `filter: drop-shadow`
> fix(Context): Rendering when filter prop is not supported

- .jest.json
- .npmignore
Cosmiconfig that PostCSS loader uses, looks for the nearest matching config from the file it's processing. It picks up Axiom's where it shouldn't, it's not needed in the NPM module so best to just ignore it when publishing.
> fix(PostCSS): Ignore PostCSS config from NPM

- src/components/context/ContextBox.css
- src/components/context/example/combinations.js
> fix(ContextBox): Adds missing separators between ContextMenu

- deploy/deploy_to_gcp.sh
Since the Sass removal and the need to generate 2 CSS files (light/dark) GCP publishing was failing. I've backdated the missing versions.
> chore(GCP): Fix publishing CSS

- package.json
- src/utils/index.js
- style-guide/client.js
- style-guide/containers/Navigation.js
- style-guide/static.js
- yarn.lock
Axiom was broken in IE11 anywhere where `find` and `includes` weren't being polyfilled. We shouldn't assume users are polyfilling these methods and should stick to ES5 methods. Removind `babel-polyfill` allows us to more reliably test brower compatibility within older browsers 🎉
> fix(browser-support): Remove ES2015 methods from src code & babel-polyfill from styleguide

- src/charts/chart-table/ChartTableRows.js
- src/charts/chart-table/ChartTableRows.test.js
- src/charts/chart-table/__snapshots__/ChartTableRows.test.js.snap
- src/charts/dot-plot/example/dot-plot-table-collapsible.js
- src/charts/dot-plot/example/index.js
Fixes:
* Removes lodash as **it's not a dependency**
* Sets height to `auto` when ChartTable is collapsable and is in the expanded state.
* Removes collapsable behaviour when no collapsable props are set. 
* Removes a workaround that was added to pass tests.
> fix(ChartTable): Collapsible behaviour

- style-guide/routes.js
- webpack.static.config.js
Looks like `'/docs/charts/bar-chart'` had been accidentally added back in... probably due to some dodgy conflict resolving 😏
> docs(StaticSite): Fixes static site generation

- src/components/base/Base.css
- src/components/base/globals.css
- src/components/form/TextArea.css
- src/components/form/TextGroup.css
- src/components/form/TextInput.css
- src/components/typography/HorizontalRule.css
This is to provide a way for those styles to be ignored through import overriding.
Partially linked to #176.
> fix(Global CSS): Moves globally applied styles to a separate file 

- package.json
Because of the weird NPM/Yarn behaviour of running `prepublish` after an `install` it errors when the directory doesn't exist.
> chore(Yarn): Fixes issues with prepublish erroring after an yarn install

- src/charts/chart-table/ChartTable.css
- src/charts/chart-table/ChartTableGrid.js
The vertical lines in the chart had a z-index applied to stack them above the dots. This caused them not to be stacked behind the body when global position was used changing their z-index context. This PR moves the vertical lines above `ax-chart-table__grid` in the DOM.
> fix(Chart Table): Fixes z-index issue

- src/components/image/ImageCircle.js
Removes a propType error when using Candytars.
> fix(ImageCircle): make src an optional requirement for ImageCircle

- src/components/position/Position.js
By default this will be document.body, but when Axiom is being used
within a wider application which uses a wrapper node, we need to ensure
the Position node remains within the wrapper.
Open to alternative approaches
> feat(Position): Adds option to specify where position nodes are appended

- README.md
- package.json
Just a suggestion, it's fine if a) there's a better way or b) it's not deemed useful enough. It just took me a little while & a little help to figure out.
> feat(Scripts): Adds a build:link script for use with npm link

- src/charts/bars/Bar.css
Fixes an issue with the horizontal bars collapsing in Safari. 
| **Before**  | **After** |
|---|---|
|<img width="493" alt="screen shot 2017-06-06 at 14 06 10" src="https://cloud.githubusercontent.com/assets/7130591/26830650/713ee764-4ac1-11e7-918b-9bb5dcd5e58e.png">|<img width="495" alt="screen shot 2017-06-06 at 14 07 45" src="https://cloud.githubusercontent.com/assets/7130591/26830680/8de2228c-4ac1-11e7-8a77-766cbe9cb255.png">|
> fix(Bars): Safari collapsing horizontal bars

- src/charts/bar-chart/BarChart.js
- src/charts/bar-chart/BarChartContext.js
- src/charts/bars/Bar.css
- src/charts/bars/Bar.js
- src/charts/bars/Bar.test.js
- src/charts/bars/__snapshots__/Bar.test.js.snap
- src/charts/bars/__snapshots__/Bars.test.js.snap
First Axiom use of `PureComponent` 🎉  In the Basic BarChart example it cuts the calls to `BarChartContext`'s render method from 63 to 21 every time the mouse enters or leaves the component. As the component isn't publicly exposed I can't think of any disadvantages to this approach.
> Feat bar chart hover

- src/components/position/Position.js
- src/components/position/example/context.js
Position/Dropdown/Tooltip and other variants are used internally throughout Axiom. Requiring everyone to remember to pass the parentNode prop to Position internally and when used by the components is a lot of effort. 
Using context like below allows it be set once in the application using it. 
```js
static childContextTypes = {
axiomPositionParentNode: PropTypes.object,
};
getChildContext() {
return {
axiomPositionParentNode: document.body.querySelector('#custom-parent'),
};
}
```
> feat(Position): Allow parentNode to be configured using context via

- src/charts/dot-plot/utils.js
When no benchmark data is provided and is not the first element it would case an error because `[undefined]` was in the elements array. This only adds it to the array if benchmark is given.
> fix(DotPlot): Formatting error when no benchmark data is given

- src/components/form/ChedioButtox.css
- src/components/form/Toggle.css
Fixes a bug where the cursor switched to `auto` while hovering over the `input` element. Also toggles, checkboxes and radio buttons are no longer user-selectable
> Toggle improvements

- src/charts/bullet-chart/BulletBars.js
- src/charts/bullet-chart/BulletBars.test.js
- src/charts/bullet-chart/BulletChart.css
- src/charts/bullet-chart/BulletChart.js
- src/charts/bullet-chart/__snapshots__/BulletBars.test.js.snap
- src/charts/bullet-chart/example/data.js
- src/charts/bullet-chart/utils.js
Fixes two issues with the bullet chart component.
1. Labels for both bars were showing this is now corrected to only show the label for the highest value in each group.
2. For smaller values the containing element was not large enough to hold the bars and labels. This has been fixed by setting a normalised height on each bar rather than the container.
> fix(bullet-chart): fix bar height for small values

- src/charts/bar-chart/BarChartBars.js
I didn't really know how to test this with the new editable example - but this is what it should be!
> fix(BarChartBars): label prop should be of type node not string

- src/charts/bullet-chart/MirroredBulletChart.js
- src/charts/bullet-chart/example/mirrored.js
Quick fix to allow the labelIndex to be passed to the sub Bullet Chart components.
> fix(MirroredBulletChart): Add control for which bar label to show.

- src/charts/dot-plot/DotPlot.css
- src/charts/dot-plot/DotPlotBenchmarkLine.js
- src/charts/dot-plot/DotPlotChart.js
> fix(DotPlot): Benchmark line is now correct height

- src/charts/chart-table/ChartTable.css
> fix(ChartTableLabel): Use lighter shade for color

- deploy/deploy_to_gcp.sh
Enable multi-threaded updates as suggested by this warning. 
> NOTE: You are performing a sequence of gsutil operations that may
run significantly faster if you instead use gsutil -m acl ... Please
see the -m section under "gsutil help options" for further information
about when gsutil -m can be advantageous.
> chore(GCP): Enable multi-threaded on acl changes

- src/components/context/__snapshots__/ContextMenuItem.test.js.snap
- src/components/form/ChedioButtox.js
- src/components/form/__snapshots__/CheckBox.test.js.snap
- src/components/form/__snapshots__/CheckBoxGroup.test.js.snap
- src/components/form/__snapshots__/ChedioButtox.test.js.snap
- src/components/form/__snapshots__/ChedioButtoxGroup.test.js.snap
- src/components/form/__snapshots__/RadioButton.test.js.snap
- src/components/form/__snapshots__/RadioButtonGroup.test.js.snap
The issue is that when a user clicks the component the event target is the `span` element, but the handler is on the sibling `input` element. This means the event bubbles up to the component's parents before the input handler is fired which makes it impossible to stop propagation. Does anyone have any better ideas about how to fix this?
This solution is a bit of a hack because I've just moved the `onClick` handler.
> fix(ChedioButtox): Pass onClick handler to Base component so event bubbling is handled correctly

- webpack.css.config.js
Fixes the CSS filename which changed in V25 due to the removal of separate theme builds.
> chore(GCP): Corrected CSS file name

- src/components/base/Base.css
- src/components/base/Base.js
- src/components/base/__snapshots__/Base.test.js.snap
Safari currently only supports `position: sticky` with a `-webkit` prefix. So the position styling needs to be in the CSS for the autoprefixing to work.
> fix(Base): Sticky behaviour to support safari css prefixing

- src/charts/bar-chart/BarChart.css
- src/charts/bar-chart/BarChart.js
- src/charts/bar-chart/BarChartBars.js
- src/charts/chart-table/ChartTable.css
- src/charts/chart-table/ChartTableRows.js
- src/charts/chart-table/__snapshots__/ChartTableRows.test.js.snap
- src/charts/chart/example/index.js
- src/charts/dot-plot/DotPlotChart.js
- src/charts/vars.css
**feat(ChartTable):** Added configurable spacing between ChartTableRows and within the grid container. This can be configured from the BarChart with the `barSpace` property using spacing pattern `x1|x2|x3`. DotPlot rows are a fixed distance of `x2`
[Netlify example of the compact version](https://599d44a37960b13543f435c5--hhogg-axiom.netlify.com/docs/charts/bar-chart?state=%7B%22BarChart%22%3A%7B%22props%22%3A%7B%22rowSpace%22%3A%22x1%22%2C%22data%22%3A%5B%7B%22label%22%3A%22Family%20%26%20Parenting%22%2C%22benchmark%22%3A14%2C%22values%22%3A%7B%22blue%22%3A17%2C%22orange%22%3A30%7D%7D%2C%7B%22label%22%3A%22Food%20%26%20Drinks%22%2C%22benchmark%22%3A7%2C%22values%22%3A%7B%22blue%22%3A10%2C%22orange%22%3A22%7D%7D%2C%7B%22label%22%3A%22Music%22%2C%22benchmark%22%3A13%2C%22values%22%3A%7B%22b …
> feat(ChartTable): Added configurable spacing between ChartTableRows

- src/components/tabset/Tab.js
- src/components/tabset/Tabset.css
Due to the uppercasing being applied to the parent `<li>` rather than the `<button>`.
> fix(Tabset): Upper casing not taking effect in Chrome and Safari

- src/components/grid/Grid.css
> fix(Grid): Correct typo in .ax-grid--horizontal-start

- .babelrc
- .gitignore
- deploy/travis_setup.sh
- package.json
Any projects that consume Axiom using Webpack will automatically find the ES modules build and tree-shake it to remove any unused components from the build!
> chore(build): Add an ES modules build with a `module` field in the package.json to enable tree-shaking with Webpack

- src/composites/change-password/ChangePassword.js
- src/composites/change-password/ChangePasswordControls.js
- src/composites/change-password/ChangePasswordForm.js
This PR prevents the ChangePassword composite's submit button pressed multiple times when there is a in the form being re rendered with an error or being closed.
> Disable submit in the ChangePassword composite once the form has been submitted

- src/components/dropdown/Dropdown.js
- src/components/position/Position.js
- src/components/tooltip/Tooltip.js
When Dropdown was disabled (using the enabled prop on Position) it would still set the visible state when clicked, and could not be taken out of the visible state because no mask had been added because it was disabled.
> fix(Dropdown): Retaining opened state when initially disabled.

- src/charts/bars/Bar.test.js
- src/charts/data-point/DataPoint.test.js
- src/charts/wordcloud/Word.test.js
- src/components/candytar/Candytar.js
- src/components/candytar/Candytar.test.js
- src/components/color-picker/ColorPickerOption.test.js
- src/components/statcard/Stat.test.js
- src/composites/usermenu/UserMenu.js
- src/index.js
- src/materials/colors/brandColors.js
- src/materials/colors/example/BrandingColors.js
- src/materials/colors/example/StringToColor.js
- src/materials/colors/example/index.js
- src/materials/colors/stringToColor.js
- src/materials/colors/stringToColor.test.js
Exports the `stringToColor` function for deterministically mapping strings to brand colors. Also factors `brandColors` out into their own module.
https://59df4c94df99536ae6588f19--axiom-rules.netlify.com/docs/materials/colors
> String to color

- src/components/base/globals.css
Google Chrome made the decision to edit their user agent stylesheet for OSX Chrome and add rounded buttons. This caused all unstyled buttons on the internet to have rounded corners. They have since reverted that change, but is not due to be released for a few months.
Further reading
https://www.chromestatus.com/features/5743649186906112
https://bugs.chromium.org/p/chromium/issues/detail?id=752450#c13
> fix(Buttons): Rounded buttons in Chrome.

- src/components/alert-bar/AlertBar.js
- src/components/alert-bar/__snapshots__/AlertBar.test.js.snap
- src/components/data-picker/DataPickerHeader.js
- src/components/horizontal-rule/HorizontalRule.js
- src/components/label/LabelIcon.js
- src/components/label/__snapshots__/LabelIcon.test.js.snap
- src/components/typography/Link.css
- src/components/typography/Link.js
Subtle link style now correctly uses the subtle text coloring, and `body` style has been added that matches the original incorrect style style.
> fix(Link): Design correction for the subtle link style.

- src/components/tabset/Tabset.css
There's definitely a more elegant solution for responsive tabs, this a quick fix to simply scroll horizontally when there's not enough room.
> fix(Tabs): Prevent breaking across multuple lines

- src/components/grid/Grid.css
- src/components/grid/Grid.js
- src/components/grid/GridCell.js
- src/components/grid/GridCell.test.js
- src/components/grid/__snapshots__/GridCell.test.js.snap
Similar to the 'shrink' option, but adds the ability to not allow the GridCell to shrink below contents size. (Equivilent of adding `flex: none` or `flex: 0 0 auto`).
> feat(Grid): Added 'none' flexing option.

- src/components/form/TextInput.js
- src/components/form/TextInput.test.js
- src/components/form/__snapshots__/TextInput.test.js.snap
By allowing use of the props from <Base> we get a bunch of really useful axiom utilities (like textCenter) to let us customise the component in a consistent way.
> fix(TextInput): Use Base under the hood to allow base props to be applied. 

- packages/axiom-charts/src/Bar/Bar.css
- packages/axiom-charts/src/Bar/Bar.js
- packages/axiom-charts/src/BarChart/BarChart.js
- packages/axiom-charts/src/BarChart/BarChartBars.js
- packages/axiom-charts/src/BarChart/BarChartContext.js
- packages/axiom-charts/src/BarChart/__snapshots__/utils.test.js.snap
- packages/axiom-charts/src/BarChart/utils.js
- packages/axiom-charts/src/BarChart/utils.test.js
- packages/axiom-charts/src/ChartTable/ChartTableRows.js
- packages/axiom-charts/src/ChartTable/ChartTableRows.test.js
- packages/axiom-charts/src/DotPlotChart/DotPlot.js
- packages/axiom-charts/src/DotPlotChart/DotPlotChart.js
- packages/axiom-charts/src/DotPlotChart/DotPlotContext.js
- packages/axiom-charts/src/DotPlotChart/DotPlotValue.js
- packages/axiom-charts/src/DotPlotChart/__snapshots__/utils.test.js.snap
- packages/axiom-charts/src/DotPlotChart/utils.js
- packages/axiom-charts/src/DotPlotChart/utils.test.js
- site/components/Documentation/Resources/Charts/BarChart.js
- site/components/Documentation/Resources/Charts/Chart.js
- site/components/Documentation/Resources/Charts/DotPlotChart.js
This PR makes the BarChart component even more appealing with a few changes.
Before the BarChart was limited to values between 0% and 100%. With the new properties `lower` and `upper` you can specify the range like you want. If you don't any of these values, the component will automatically take the lowest and highest value from the passed data.
Sometimes you want to show more than just a boring number in your BarChart. With the new property `barLabel` you can easily append units like a percentage sign or return a rich component and go wild.
I'm sorry, this PR contains a few breaking changes:
1. To retain the previous behaviour of the `BarChart` and `DotPlotChart` with values going from 0 up to 100, you have to pass `lower=0` and `upper=100` to not let the new behaviour kick-in. Otherwise …
> feat(BarChart):  Flexible labels and absolute data support

- packages/axiom-charts/src/index.js
- packages/axiom-charts/src/utils/__snapshots__/axisUtils.test.js.snap
- packages/axiom-charts/src/utils/axisUtils.js
- packages/axiom-charts/src/utils/axisUtils.test.js
Now that the BarChart can display absolute values instead of just percent, I added this axis helper providing: 
* `axiUtilsgetAxisUpper([25, 41, ...])`
Calculates an upper based on a array of values to be charted. This is still pretty dumb, as it'll always choose the next power of 10 based on the maximum value used.
* `axisUtils.getEquallyDistributedAxisLabels(upper, lower, tickCount = 5, labelFormatter)`
Generates labels for equally distributed ticks between upper and lower.
> feat: adds an axis utils

- packages/axiom-charts/src/utils/axisUtils.js
- packages/axiom-charts/src/utils/axisUtils.test.js
In https://github.com/BrandwatchLtd/axiom/pull/485 `axisUtils.getAxisUpper()` was added which returned an upper of the next magnitude of the maximum e.g. for a max of `101` we returned `1000`. This wastes way too much space on graphs.
This PR changes the behaviour of `axisUtils.getAxisUpper()` to round up to the next multiple of the _same_ magnitude, e.g.
|max|result|
|-|-|
|0.43|0.5|
|3|10|
|203|300|
|950|1000|
> fix(axisUtil.getAxisUpper) rounds to same order of magnitude instead 

- packages/axiom-charts/src/ChartTable/ChartTableRows.js
- packages/axiom-charts/src/ChartTable/__snapshots__/ChartTableRows.test.js.snap
When using `tinyNumber` formatter on `xAxisLabels` on the bar chart, the last label is breaks on the thinspace for large numbers.
I'd argue labels on this chart should never break.
Before:
After:
> fix(BarChart) do not break labels with (thin)spaces

- packages/axiom-components/src/AlertDialog/AlertDialog.js
- packages/axiom-components/src/AlertIcon/AlertIcon.css
- packages/axiom-components/src/Card/Card.css
- packages/axiom-components/src/Card/Card.js
- packages/axiom-components/src/DataPicker/DataPicker.js
- packages/axiom-components/src/DataPicker/__snapshots__/DataPicker.test.js.snap
- packages/axiom-components/src/Dialog/Dialog.js
- packages/axiom-components/src/Modal/Modal.css
- packages/axiom-components/src/Modal/Modal.js
- packages/axiom-components/src/Platform/ConsoleHeader.js
- packages/axiom-components/src/Platform/ConsoleMenu.css
- packages/axiom-components/src/Platform/Platform.css
- packages/axiom-components/src/Platform/Platform.js
- packages/axiom-documentation-viewer/src/DocumentationMenu.css
- packages/axiom-documentation-viewer/src/DocumentationShowCase.js
- packages/axiom-materials/src/colors.css
- packages/axiom-materials/src/colors.js
- packages/axiom-materials/src/index.js
- packages/axiom-materials/src/opacities.css
- packages/axiom-materials/src/opacities.js
- packages/axiom-materials/src/sizing.css
- packages/axiom-materials/src/theme-day.css
- packages/axiom-materials/src/theme-night.css
- site/components/Documentation/Resources/Components/Card.js
- site/components/Documentation/Resources/Materials.js
- site/components/Documentation/Resources/Materials/Themes.js
Introduces a better way to handle Cards, Shadows and general variable background colours across the day and night themes. 
Notable breaking changes is mainly around Cards. 
* Configurable elevation is now not a thing. Simply use the flag `shadow` and see the Card matrix in the new documentation. 
* `color` property has been removed as the values did not work for the night theme. Use the new `shade` pattern. 
Other breaking changes that are unlikely to effect anyone updating include, some CSS variable changes and a prop removal from Modal. Please see commit messages and CHANGELOGs for more information. 
[Netlify Deploy](https://new-ui-colours--hhogg-axiom.netlify.com/)
> New UI Colours, Shadows and Shading pattern. 

- packages/axiom-components/src/Select/Select.js
The `this.handleClear` wasn't used inside Select.
> fix(Select): Only add onClear 'X' when an onClear is given

- packages/axiom-charts/src/BarChart/BarChart.js
- packages/axiom-charts/src/BarChart/utils.js
- packages/axiom-charts/src/BarChart/utils.test.js
When using the BarChart with multiple bars per label and hovering over a single bar on a label, other bars on that label are dimmed and on other labels the bars of different colour are hidden.
This does not make sense if you use just one bar per label, as there is no need to focus the users attention:
With this PR the BarChart will not hide if there is just **one** bar per label. If any label has more than one bar, the behaviour is the same as before.
> fix(BarChart): hide other bars only when BarChart displays multiple bars

- .travis.yml
- package.json
- scripts/validate_commit_messages.sh
Since we rely on the commit message for auto publishing new versions, we should validate them to ensure a new `npm publish` gets triggered after a PR is merged. 
This build proves that validating is working https://travis-ci.org/BrandwatchLtd/axiom/builds/359252903
> Validate commit message to ensure correct format

- packages/axiom-charts/src/Bar/Bar.css
- packages/axiom-charts/src/Bar/Bar.js
- packages/axiom-charts/src/DataPoint/DataPoint.js
- packages/axiom-charts/src/DataPoint/DataPoints.css
- packages/axiom-charts/src/Line/Line.css
- packages/axiom-charts/src/Line/Line.js
- packages/axiom-charts/src/Line/LinePoint.js
- packages/axiom-materials/src/colors.css
- packages/axiom-materials/src/colors.js
- site/components/Documentation/Resources/Materials/Colors.js
- fixed the typo ` --color-sentiment-neagtive` and marked it as a fix, as I didn't see it anywhere used on github
- Added the color `sentiment-neutral` as specified by @lilybrandwatch
- addes support for  sentiment colors for `Bar` and `DataPoint` components
> STS-81 allow sentiment colors in bar chart

- .travis.yml
- yarn.lock
After running `lerna bootstrap` I immediately had a modified `yarn.lock` because the lockfile wasn't updated after the `package.json` was changed. With this change, changes to the `package.json` without updating the lockfile are detected and will fail CI.
Ideally I would do this with the yarn option `--frozen-lockfile` but I have no idea how to do that with lerna. The only option I found was to add it to `npmClientArgs` in `lerna.json` but then it would also freeze the lockfile in development which is quite inconvenient.
> chore(CI): Detect modified yarn.lock on CI

- package.json
When I tried to run all tests locally, some of the tests were failing for me because of different timezones. This PR always sets the same timezone for testing. I am not sure if this is the cleanest solution, but it works.
> chore(tests): Always run tests in same timezone

- packages/axiom-charts/src/utils/axisUtils.js
- packages/axiom-charts/src/utils/axisUtils.test.js
This guards against getting duplicate axis labels, of e.g. [0, 0, 0] for e.g. 
```js
axisUtils.getEquallyDistributedAxisLabels({upper=0, lower=0})
```
In case upper and lower are equal, just return no labels at all.
This currently causes React to loose track of the labels, as it sets a `key` of the label [here](https://github.com/BrandwatchLtd/axiom/blob/ec6eb66314f2014337318476b8308f09a1a9e99d/packages/axiom-charts/src/ChartTable/ChartTableRows.js#L66). This should probably be fixed separately as well.
> fix(axisUtils): when upper and lower are equal return no labels

- packages/axiom-components/src/Context/Context.css
- packages/axiom-components/src/Dropdown/Dropdown.js
- packages/axiom-components/src/Position/Position.css
- packages/axiom-components/src/Position/Position.js
- packages/axiom-materials/src/sizing.css
Also fixes an issue where preprocessing (and not preserving) CSS custom properties would cause the context components to be inset by the size of the arrow.
> fix(Position): Reduces offset when arrow is not used

- packages/axiom-charts/src/Bar/Bar.css
- packages/axiom-charts/src/Bar/Bar.js
- packages/axiom-charts/src/DataPoint/DataPoint.js
- packages/axiom-charts/src/DataPoint/DataPoints.css
- packages/axiom-charts/src/Line/Line.css
- packages/axiom-charts/src/Line/Line.js
- packages/axiom-charts/src/Line/LinePoint.js
Adds support for social colors for all chart types.
> feat(charts): add support for social colors

- packages/axiom-charts/src/BarChart/BarChart.js
When `data` for a BarChart contains multiple labels with the same name, one will remain in the chart after re-rendering different data.
This is due to the label being used as a `key`.
To fix this, we'll always use `index` as key, so React doesn't lose track of these elements.
> fix(BarChart): fix stale label when using duplicate labels

- packages/axiom-components/src/Context/Context.css
- packages/axiom-components/src/Context/Context.js
- packages/axiom-components/src/Context/ContextContent.js
- packages/axiom-components/src/Context/ContextMenu.js
- packages/axiom-components/src/Context/__snapshots__/ContextContent.test.js.snap
- packages/axiom-components/src/Context/__snapshots__/ContextMenu.test.js.snap
- packages/axiom-components/src/Dropdown/DropdownContent.js
- packages/axiom-components/src/Dropdown/DropdownContext.js
- packages/axiom-components/src/Dropdown/DropdownFooter.js
- packages/axiom-components/src/Dropdown/DropdownHeader.js
- packages/axiom-components/src/Dropdown/DropdownMenu.js
- packages/axiom-components/src/Dropdown/DropdownMenuItem.js
- packages/axiom-components/src/index.js
- site/components/Documentation/Resources/Components/Dropdown.js
This was technically already kind of possible, except for:
* a bug with the placement of the separator on a scrollable list (6a95a67)
* compact content area with smaller vertical padding (055f3d8)
I also added an alias component for `DropdownHeader` and `DropdownFooter` (e517994), although these aren't really needed so happy to drop off if anybody thinks they are just noise. 
I also moved over the propType docs to Dropdown (5f514a4) , because the lower level Context components do not appear in the Style Guide.
> Sticky Dropdown Header and Footer example. 

- packages/axiom-components/src/Context/ContextMenuItem.js
In #538 I added the indeterminate state to checkboxes, but forgot to pass it down to the checkbox in the `ContextMenuItem` component.
> fix(ContextMenuItem): Pass down indeterminate property to checkbox

- packages/axiom-components/src/Table/Table.css
- packages/axiom-components/src/Table/TableRow.js
- packages/axiom-components/src/Table/TableRow.test.js
- packages/axiom-components/src/Table/__snapshots__/TableRow.test.js.snap
Adds a `hasBorder` property to TableRow and TableCell to allow for borderless rows and cells.
> feat(TableRow): adds a hasBorder property to TableRow and TableCell

- packages/axiom-components/src/Context/Context.css
- site/components/Documentation/Resources/Components/Dropdown.js
[Deploy Link](https://5ae98e0bc965926325846456--youthful-albattani-41ebb2.netlify.com/docs/packages/axiom-components/dropdown)
As discussed with @HHogg - this PR fixes separator lines being drawn after submenus in Dropdowns.
Also fixed the example for dropdowns, where the submenu was wrapped in an own `DropdownMenu`.
> Fix redundant separator after submenu

- packages/axiom-charts/src/BarChart/BarChart.css
- packages/axiom-charts/src/BarChart/BarChartBars.js
We need to have more control over the bar label which currently sits in the `Bar` component. This PR disables the default label by passing `showLabel: false` and adds a new label to `BarChartBars` itself. 
[Demo](https://brave-keller-55c6a8.netlify.com/docs/packages/axiom-charts/bar-chart)
> refactor(BarChartBars): Move label from Bar to upper component

- packages/axiom-components/src/Dropdown/DropdownContext.js
`onRequestCloseDropdown` was added as a way to access the `closeDropdown` without using react context... but when it's not needed it was still be spread onto the Context causing a console error.
> fix(Dropdown): Omit onRequestCloseDropdown from reaching DropdownContext

- packages/axiom-charts/src/Bar/Bar.css
- packages/axiom-charts/src/Bar/Bar.js
- packages/axiom-charts/src/Bar/Bar.test.js
- packages/axiom-charts/src/Bar/__snapshots__/Bar.test.js.snap
- packages/axiom-charts/src/Bar/__snapshots__/Bars.test.js.snap
- packages/axiom-charts/src/BulletChart/__snapshots__/BulletBars.test.js.snap
Adding a new property `fillMode` to apply a different background texture. [Demo](https://brave-keller-55c6a8.netlify.com/docs/packages/axiom-charts/bars/)
> feat(Bar): Add new prop striped

- packages/axiom-charts/src/BarChart/BarChart.js
- packages/axiom-charts/src/BarChart/BarChartBars.js
Right now if you only use one bar per row, and you hover a row, all rows with the same color are highlighted which in that case is not the desired result (we just want to highlight the actual hovered row).
> fix(BarChart): Do not highlight all bars with same color if there is only one bar per row

- packages/axiom-charts/src/BarChart/BarChart.js
- packages/axiom-charts/src/BarChart/BarChartBars.js
- packages/axiom-charts/src/BarChart/CombinedBar.css
- packages/axiom-charts/src/BarChart/CombinedBar.js
- packages/axiom-charts/src/BarChart/CombinedBar.test.js
- packages/axiom-charts/src/BarChart/__snapshots__/CombinedBar.test.js.snap
Adds a new  prop `showDifferenceArea` to the BarChart component. Setting this property to `true` (`false` by default) will cause the BarChart to add a striped bar between the bar and benchmark line (see attached screenshot). 
[Demo](https://brave-keller-55c6a8.netlify.com/docs/packages/axiom-charts/bar-chart)
> feat(BarChart): Add new prop showDifferenceArea

- packages/axiom-components/src/Button/Button.css
This was a bit weird, maybe some browser weirdness/bug, where clicking on an element inside the button would apply the :active state when it was :disabled (clicking on anywhere else on the button would not do this). 
**Before**
**After**
> fix(Button): Active state being applied when clicking on svg element

- packages/axiom-charts/src/BarChart/BarChart.js
- packages/axiom-charts/src/DotPlotChart/DotPlotChart.js
- packages/axiom-charts/src/LineChart/LineChart.js
- site/components/Documentation/Resources/Charts/BarChart.js
- site/components/Documentation/Resources/Charts/DotPlotChart.js
- site/components/Documentation/Resources/Charts/LineChart.js
**BREAKING CHANGE:** The BarChart now only accepts a method for the xAxisLabel property instead of an array. The method receives a "lower" and an "upper" argument and expects an array to be returned.
Currently you can pass in an array of strings to render the labels on the x-axis. In order to enable more dynamic rendering this is changed to be a method now. It should still return an array of strings.
Updating existing code should be straight-forward by just wrapping the array in a method:
```javascript
<BarChart xAxisLabel={ ['0', '50', '100'] } />
// should be changed to this:
<BarChart xAxisLabel={ (lower, upper) => ['0', '50', '100'] } />
```
> feat(BarChart): Changed xAxisLabel property to be a method that returns an array of labels

- packages/axiom-charts/src/BarChart/BarChart.css
When using `size` the label next to the bar is not vertically centered anymore:
Set height to `100%` and center it with flexbox.
> fix(BarChart): vertically center label when size is specified

- packages/axiom-charts/src/BarChart/BarChartBars.js
- packages/axiom-charts/src/BarChart/CombinedBar.js
- packages/axiom-charts/src/BarChart/CombinedBar.test.js
- packages/axiom-charts/src/BarChart/__snapshots__/CombinedBar.test.js.snap
There is a need to be able to add two tooltips on a striped bar. This PR is in preparation for the actual PR which I will raise soon. It moves `ChartContext` into `CombinedBar` and to retain the previous behaviour.
> refactor(CombinedBar): To accept tooltip and dropdown props

- packages/axiom-components/src/List/List.css
The inline-block styling causes the height to bump to 21px.
> fix(List): Fixes erroneous line-height by using flex

- packages/axiom-components/src/List/List.css
There's been quite a few issues caused by these changes. We'll revisit the original issue but as it's just an extra px, just reverting it back to the original state for now.
> fix(List): Reverts changes made in #575, #579 and #583.

- packages/axiom-components/src/AlertDropdown/AlertDropdown.js
- packages/axiom-components/src/Base/Base.css
- packages/axiom-components/src/Base/Base.js
- packages/axiom-components/src/DataPicker/__snapshots__/DataPicker.test.js.snap
- packages/axiom-components/src/Dropdown/Dropdown.js
- packages/axiom-components/src/Dropdown/DropdownContext.js
- packages/axiom-components/src/Position/Position.css
- packages/axiom-components/src/Position/Position.js
**Affected components**
* Dropdown
* AlertDropdown
* Select
* Datepicker
**Background**
The current implementation adds a mask to the DOM when a dropdown is open. This mask captures click events outside of the dropdown and causes the dropdown to be closed. This caused an undesirable double click when navigating between form elements. We wish to remove the mask, removing a click from the users flow.
**Approach**
This PR has proved challenging and I've tried a few different approaches. The one i've settled on is using a custom HOC and disabling pointer events. I could get no other approach to fully meet all the requirements. 
The `onclickoutside` HOC is used to wrap the dropdown source. This adds an event listener to the DOM which is then used to trigger closing of the dropdown. It was …
> feat(Dropdown): Remove dropdown mask

- packages/axiom-components/src/Form/InputWrapper.css
- packages/axiom-components/src/Form/InputWrapper.js
- packages/axiom-components/src/Form/TextInput.css
- packages/axiom-components/src/Form/TextInput.js
- site/components/Documentation/Resources/Components/Dropdown.js
Currently when a `readOnly` `TextInput` is used as a `DropdownTarget` the onHover cursor is a set to `text`. This is confusing as the input is not editable and onClick triggers the dropdown opening. This PR add an option to the `TextInput` to allow the cursor to be set to `pointer` in this situation. 
https://5b2b8489b13fb1210a8fbb0a--president-randy-42828.netlify.com/docs/packages/axiom-components/dropdown
> feat(Add option to change cursor on text input)

- packages/axiom-components/src/Tooltip/Tooltip.js
- packages/axiom-components/src/Tooltip/TooltipTarget.js
Gives the option of adding a one second delay to the opening of a tooltip (UX requirement)
https://tooltip-display-delay--andyp-axiom.netlify.com/docs/packages/axiom-components/tooltip
> feat(Tooltip): Adds boolean delay option

- packages/axiom-components/src/DataPicker/__snapshots__/DataPicker.test.js.snap
- packages/axiom-components/src/Dropdown/Dropdown.js
- packages/axiom-components/src/Dropdown/DropdownContext.js
- packages/axiom-components/src/Dropdown/DropdownTarget.js
In the work to remove the dropdown mask it was nessacary to disable pointer events from on the Dropdown Target. This was nessacary to avoid the double open bug caused by simultaneous firing of a `focus` & `click` event. 
This cause two problems
1. When the child of the Dropdown target was a DOM element it was being passed the prop `pointerEventsDisabled` this caused an error and did not disable pointer events.
2. On hover affects on the Dropdown target were lost when the dropdown was open.
This PR addresses these issues by replacing the `pointerEventsDisabled` approach with some state within `DropdownTarget` to avoid the double open bug.
Preview
https://5b34b634dd28ef2de9fff4a1--nostalgic-curie-a20a02.netlify.com/docs/packages/axiom-components/dropdown
> fix(Dropdown): Restore pointer events

- packages/axiom-components/src/Position/Position.js
This is a fix to positioning issue in various places. Popper defaults to it's boundaries element being the nearest scroll container. However when ever overflow is used it will effect the positioning by trying to keep it within those bounds. 
This contextual menu should be displayed central as there is more than enough room on either side.
This contextual menu is targeting an element inside the console (a scroll area) however it should be positioned out over the canvas area where there is enough room. 
To change the default from the nearest scroll parent to the viewport. This seems like the most common use case for positioning for our layouts. I'm not sure it's needed but we can always add an `boundariesElement` prop to the `Position` component to allow it to be configured, but I'm not …
> fix(Position): Boundary element to be viewport

- scripts/publish_packages.sh
Travis uses `https://...` as repo url, so the whole ssh key will not even be used 😢 
Another try by adding a remote using the git+ssh and passing that to lerna.
> chore(CI): use git remote with ssh

- scripts/publish_packages.sh
Should have been `git remote add ...` instead of `git add remote ...` 😿
> Chore(CI): fix adding remote for publishing packages

- packages/axiom-components/src/Dropdown/DropdownTarget.js
In the screenshot above, the row around the menu button is clickable. If the ellipsis menu is clicked we prevent propagation to stop the row action being triggered.
In the latest version of Axiom the callback doesn't get triggered if the `focusEventHasFired`, making it impossible to stop the propagation.
This fix hopefully addresses that, although I don't have much context as to the recent work in this area, so hopefully it doesn't cause any additional regression.
> fix(DropdownTarget): Ensures callback property is always fired

- packages/axiom-components/src/Context/__snapshots__/Context.test.js.snap
- packages/axiom-components/src/Tip/Tip.js
- packages/axiom-components/src/Tip/__snapshots__/Tip.test.js.snap
- site/components/Documentation/Resources/Components/Tip.js
- This PR removes the default color from the tip. This introduced a bug into all components that were using Context. 
Here's the deploy branch. : https://5b572ad2e39e7c1d2253a11c--affectionate-mcclintock-42eb2e.netlify.com/
> Remove default color from tip

- packages/axiom-components/src/Context/Context.css
- packages/axiom-components/src/Tip/Tip.css
The variable seems to have been off and therefore the tip wasn't positioned correctly when position=top.
> fix(Tip): Properly position tip when position is top

- packages/axiom-charts/src/BarChart/BarChart.js
Before all benchmark lines where faded out, when you hovered over a bar.
This PR fades out only other benchmark lines, analog to fading out other bars.
Before:
After:
[netlify link](https://5b5f19014ed62f5581dd80b7--youthful-albattani-41ebb2.netlify.com/docs/packages/axiom-charts/bar-chart)
> fix(BarChart): only fade other benchmark lines

- scripts/publish_packages.sh
This is a followup on https://github.com/BrandwatchLtd/axiom/pull/624
The line to set npm config variable was faulty.
- It was missing the config key `registry`
- npm nowadays will throw an error when the protocol is missing
Hope this fixes the publishing 😓
> chore(npmAuth): fix npm config call

- .nvmrc
- scripts/publish_packages.sh
So did some further testing with a test package, where I could really test publishing without affecting axiom:
|node version|lerna version||
|-|-|-|
|10.7.0|2.8.0| 😢 failed with `lerna ERR! publish Ran out of retries while publishing....` (same error we saw on travis before my "fix")|
|10.7.0|3.0.0-rc.0| 😢 failed with `lerna ERR! yarn publish --ignore-scripts --new-version 0.0.25 --non-interactive exited ENOENT in ...`|
|v8.11.3 (lts/carbon)|2.8.0|🎉publishing works  |
There was already a bug filed for this in https://github.com/lerna/lerna/issues/1515
So
1. reverting https://github.com/BrandwatchLtd/axiom/pull/638 (although not really documented in the docs of `npm config` how it was before is the way to go).
2. use `lts/carbon` in `.nvmrc`
> Another attempt to fix publishing

- packages/axiom-charts/src/BarChart/BarChart.js
- packages/axiom-charts/src/BarChart/BarChartBars.js
- packages/axiom-charts/src/ChartTable/ChartTable.css
When you hovered over the benchmark line other rows have lost their fade state.
The root cause for this is that the selected row is set when you hover over a bar and the benchmark line is not part of the bar.
This PR fixes this by introducing a separate state, when you hover over the over a row, by just setting `selectedIndex`. When you hover over over a bar the `selectedColor` then set.
This made it possible to keep the other rows faded, when you hovered over the benchmark line.
(Sorry about the grey background artifacts, seems licecap is bugged out by them when recording the gifs)
~~[netlify link](https://5b603b22b13fb10a278ecf2b--youthful-albattani-41ebb2.netlify.com/docs/packages/axiom-charts/bar-chart)~~
[netlify link](https://5b62f443dd28ef3382c20440--youthful-albattani-41ebb2.netlif …
> feat(BarChart): highlight row when mouse is anywhere inside the row

- packages/axiom-charts/src/BarChart/CombinedBar.js
`BarChartBars` expects `data` to be a object, which is correct. It passes `data` simply along to `CombinedBar`, hence `CombinedBar` should expect also an object.
> fix(BarChart): fix CombinedBar data prop type

- scripts/publish_packages.sh
Lerna made a switch to use the `npmClient` option for publishing as well as installing, which then use the registry of that npm client, rather that the registry we're setting with the auth token. 
```
lerna ERR! publish error An unexpected error occurred: "https://registry.yarnpkg.com/@brandwatch%2faxiom-components: You must be logged in to publish packages.".
```
This switches back to using the standard `npm` client for publishing ... hopefully this will get it working again.
> chore(Publishing): Use npm client for publishing with lerna

- packages/babel-plugin-axiom-imports/src/__snapshots__/babel-plugin-axiom-imports.test.js.snap
- packages/babel-plugin-axiom-imports/src/babel-plugin-axiom-imports.js
- packages/babel-plugin-axiom-imports/src/babel-plugin-axiom-imports.test.js
- packages/babel-plugin-axiom-imports/test/property.js
The import plugin was incorrectly stripping the string literal property accessors, when transform object names (from imports). 
This was breaking the icons because inside the Icon component there was this ....
```js
if (icons[name]) {
return null;
}
```
Which was incorrectly changed to...
```js
if (!_icons2.default.name) {
return null;
}
````
Now changes it to...
```js
if (!_icons2.default[name]) {
return null;
}
```
> fix(babel-plugin-axiom-imports): Member expression literals transform

- packages/axiom-components/src/DatePicker/DatePicker.js
- packages/axiom-components/src/DatePicker/DatePickerContext.js
- packages/axiom-components/src/DatePicker/DatePickerControls.js
- packages/axiom-components/src/DatePicker/DatePickerRangeSelection.css
- packages/axiom-components/src/DatePicker/DatePickerRangeSelection.js
- packages/axiom-components/src/DatePicker/DatePickerSelection.js
- packages/axiom-components/src/DatePicker/SelectedDateOrRangePropTypes.js
- site/components/Documentation/Resources/Components/DatePicker.js
The DatePicker can now offer _quick selections_ for ranges to the user.
These quick selections can be specified by setting the prop `rangeQuickSelections` in the form of e.g. 
```js
[
{
label: 'Today',
range: 'P1D',
},
{
label: '7D',
range: 'P7D',
},
{
label: '14D',
range: 'P14D',
},
{
label: '1M',
range: 'P1M',
},
{
label: '2M',
range: 'P2M',
},
]
```
The quick selection ranges are only shown if the component has
* `rangeSelect`
* `rangeQuickSelections` not set to `null` or an empty array.
When the user clicks on of these the `onSelect` callback is called with the `range` of the quick selection clicked.  It's then up to the application to convert the `range` into `startDate` and `endDate` and update these properties on the `DatePicker` so that the clicked range is selected.
This allows …
> feat(DatePicker): add quick selection

- packages/axiom-charts/src/ChartLayout/ChartLayout.css
- packages/axiom-charts/src/ChartLayout/ChartLayoutLabels.js
- packages/axiom-charts/src/LineChart/LineChart.js
- site/components/Documentation/Resources/Charts/LineChart.js
- site/components/Documentation/Resources/Charts/chartData.js
`LineChart` uses `ChartLayoutLabels` to position the labels on the x- and y-axis. 
On the y-axis it supports the [`precise mode`](https://github.com/BrandwatchLtd/axiom/blob/master/packages/axiom-charts/src/ChartLayout/ChartLayoutLabels.js#L33), i.e. you specify the exact position with 
```js
[
{
label: <text>,
value: <number>,
},
...
]
```
The value is then converted, based on `upper` and `lower`, to the range of `0-100%`.
For the x-axis the `precise mode` is not supported. Instead the passed labels are [positioned with flexbox](https://github.com/BrandwatchLtd/axiom/blob/8c021a1f5aee0443756efc3e9fd9a6b39e76a945/packages/axiom-charts/src/ChartLayout/ChartLayout.css#L30-L31). Though that seems wrong as
* it enforces the consumer to use labels, that match the positioning of flexbox
* …
> precise mode in line chart x axis

- packages/axiom-components/package.json
- packages/axiom-components/src/Context/Context.css
- packages/axiom-components/src/Dropdown/DropdownContext.js
- yarn.lock
Related ticket: [AX-53](https://office.brandwatch.com/jira/browse/AX-53)
Fixes: [TOP-853](https://office.brandwatch.com/jira/browse/TOP-853) & [STS-160](https://office.brandwatch.com/jira/browse/STS-160)
[Netlify](https://5b8eb280dd28ef7b7f4716af--priceless-benz-91b798.netlify.com/docs/packages/axiom-components/dropdown)
Previously hover and focus styles were separate and you could get into a state where both were bing applied on two menu items. Now the blue highlight can only be applied to a single item even when switching between mouse and keyboard menu navigation.
old:
new:
> fix(Dropdown): Implement native style hover and focus

- packages/axiom-components/src/Form/TextInput.js
- packages/axiom-components/src/Form/__snapshots__/TextInput.test.js.snap
- packages/axiom-components/src/Select/__snapshots__/Select.test.js.snap
- site/components/Documentation/Resources/Components/Form.js
This fixes an issue that was introduced in 4.11.0 (https://github.com/HHogg/axiom/commit/bc3072c) where because the inputWrapper was moved inside of the TextInput's input container, the bottom-margin of `ax-space--x4` would no longer appear as it would always be the last child.
This adds a `space` property to the TextInput's container to rectify this. 
I've also made it so the documentation showcases for TextInputs and TextAreas now have at least one case of two inputs in a showcase area so that it is easier to notice these issues in development
> Fix input container spacing

- packages/axiom-components/src/Grid/Grid.js
- packages/axiom-components/src/Grid/Grid.test.js
- packages/axiom-components/src/Grid/GridCell.js
- packages/axiom-components/src/Grid/GridCell.test.js
- packages/axiom-components/src/Grid/__snapshots__/Grid.test.js.snap
- packages/axiom-components/src/Grid/__snapshots__/GridCell.test.js.snap
Following scenario. 
I want to create a table using Axiom Grid. The table consist of two columns ID and name. The ID column needs to have a background image. Axiom doesn't except the `className` property for `GridCell` which is the reason why I added a `div` as a children of `GridCell`. Not very nice, but it works. 
```js
<Grid>
<GridCell>
<Grid>
<GridCell>
<div className="pattern-background">2</div>
</GridCell>
<GridCell>Smith</GridCell>
</Grid>
</GridCell>
<GridCell>
<Grid>
<GridCell>
<div className="pattern-background">3</div>
</GridCell>
<GridCell>Williams</GridCell>
</Grid>
</GridCell>
<GridCell>
<Grid>
<GridCell>
<div className="pattern-background">5</div>
</GridCell>
<GridCell>Rodriguez</GridCell>
</Grid>
</GridCell>
</Grid>
```
However, now there is this other requirement that the …
> Support className on `Grid` and `GridCell`

- packages/axiom-components/src/Base/Base.js
- packages/axiom-components/src/Form/TextInput.js
This PR adds the ability to focus TextInput in axiom. This is to avoid looking for the `input` tag and using `findDOMNode` in every app that uses `TextInput` and instead providing a way to do this in axiom.
> fix(TextInput): Add ability to focus TextInput in axiom.

- packages/axiom-components/src/Context/ContextMenuItem.js
- packages/axiom-components/src/Context/__snapshots__/ContextMenuItem.test.js.snap
BREAKING CHANGE: ContextMenuItem's onClick event now stops Propagation.
https://office.brandwatch.com/jira/browse/AX-109
There may have been multiselect dropdowns with their onClicks built to account for this. Now that the event doesn't trigger three times when clicking the checkbox, there may be unintended side effects
> feat(ContextMenuItem): stop multiselect mode triggering onClick 3 times

- packages/axiom-components/src/Form/TextInput.js
This PR adds a number type option to the `TextInput` component, allowing us to use HTML number fields.
> feat(TextInput): Add "number" option to type prop.

- packages/axiom-components/src/Base/Base.js
- packages/axiom-components/src/Typography/Text.css
The `Base`-component accepts a limited number of values for the `textColor` property. I want to make use of the `sentiment-negative`, `sentiment-positive` and `sentiment-neutral` colors as well.
> feat(Base): Enable "sentiment-positive/negative/neutral" as textColor

- README.md
- lerna.json
- package.json
- yarn.lock
Updating lerna to v3 and remove need of having lerna installed globally by using a postinstall hook.
> Bump lerna to v3

- packages/axiom-components/src/CardGraphic/Ghost.css
- packages/axiom-components/src/CardGraphic/Ghost.js
- packages/axiom-components/src/index.js
- site/components/Documentation/Resources/Components.js
- site/components/Documentation/Resources/Components/CardGraphic.js
*WARNING - contains animation*
First Card Graphic for use in areas like No Results, there are more designs to follow. Uses CSS and SVG animations, displays ok in Edge and IE11 but doesn't animate. (I ran out of time it's a Funky Friday) 
https://5bdc7bdadd28ef73995b5c69--andyp-axiom.netlify.com/docs/packages/axiom-components/card-graphic
Chrome
Safari
Firefox
Edge
IE11
> feat(Ghost): Adds ghost card

- packages/axiom-components/src/Form/InputWrapper.css
Right now TextInputs are rendered with a width of 0px in IE11. Seems like IE11 is behaving differently than Chrome or Firefox when using `flex-basis: 0%`. This change fixes the width in IE11 while the behaviour remains unchanged for Firefox and Chrome.
> fix(TextInput): Fix text input size in IE11

- packages/axiom-components/src/UsageHint/UsageHint.js
Currently there's no way to change the width of the UsageHint, it takes the default off of the dropdown  context which is `14.5rem`. In the frontend Analytics we would find the addition of this width very useful.
https://kind-hodgkin-6e93e5.netlify.com/docs/packages/axiom-components/usagehint/
> feat(UsageHint): Consume width on dropdown context.

- packages/axiom-components/src/Transition/Transition.css
This PR adds overflow hidden in y-direction to the Transition component so the scrollbar does not show up.
> feat(Transition): Adding overflow hidden in y-direction

- packages/axiom-components/src/Context/Context.css
Came across this issue trying to add [react-virtualized](https://github.com/bvaughn/react-virtualized) inside a DropdownMenu.
In this case the containing component tries to get it's height from the surrounding container.
For the DropdownMenu that is the div with the `.ax-context-menu`. But it does not set any height, nor max-height, when passing height/max-height to the DropdownMenu, resulting in a height of 0.
By always setting `height: 100%` for `.ax-context-menu`, it takes the full height of it's parent, if it has a height/max-height is set on it.
So this does not interfere with using the Context/DropdownMenu without height nor maxHeight, but allows children to determine the available space.
> fix(ContextMenu): set ax-context-menu to full height

- packages/axiom-components/src/Context/Context.css
- packages/axiom-components/src/Context/ContextMenu.js
- packages/axiom-components/src/Context/__snapshots__/ContextMenu.test.js.snap
- packages/axiom-components/src/Dropdown/DropdownMenu.js
When using react-virtualized, the vertical padding of the scrollable container must be defined in a lower component, so the scrollbar spans over the complete container.
This PR allows the vertical padding to be configurable in a dropdown. The default is like before.
> feat(DropdownMenu): allow paddingVertical to be configurable

- packages/axiom-components/package.json
- packages/axiom-components/src/Validation/Validate.js
- packages/axiom-components/src/Validation/Validate.test.js
- packages/axiom-components/src/Validation/Validation.js
- packages/axiom-composites/src/ChangePasswordDialog/ChangePasswordDialog.js
- packages/axiom-composites/src/FormInputs/ConfirmPasswordInput.js
- packages/axiom-composites/src/FormInputs/CurrentPasswordInput.js
- packages/axiom-composites/src/FormInputs/NewPasswordInput.js
If you change the `required` property of a form input the `Validate` component does not update to reflect the change.
Each form input has a `Validate` wrapper.
A forms `Validates` are managed by the `Validation` component.
A forms `Validates` are now added when in `componentDidUpdate` lifecycle method. Previously `Validation` stored a form `Validators` as an array and used the index to manage removal and edit. `Validators` is now a map with unique ID's.
Example use case, radio button makes `in new folder` input required.
> fix(Validate): Make validation on form element dynamic

- packages/axiom-charts/src/DataPoint/DataPoint.js
- packages/axiom-charts/src/DataPoint/DataPoints.css
Adds the `warning` `success` and `error` colors to DataPoint (this is needed for the upcoming Instagram Hashtags work).
> feat(DataPoint): Added ui colors (warning, success, error) to DataPoint

- packages/axiom-components/src/Context/Context.css
- packages/axiom-components/src/EllipsisTooltip/EllipsisTooltip.js
- packages/axiom-components/src/index.js
- site/components/Documentation/Resources/Components.js
- site/components/Documentation/Resources/Components/EllipsisTooltip.js
Adding a `EllipsisTooltip` that shows a tooltip when the text clipped due to not enough width available.
This is needed for DropdownMenuItems that is forced to have a fixed height (e.g. when used in combination with [react-window](https://github.com/bvaughn/react-window). Long content should be hidden with an ellipsis but but still be shown when hovered over.
[Demo EllipsisTooltip](https://brandwatch-axiom-tomru.netlify.com/docs/packages/axiom-components/ellispsistooltip)
[Demo inside Dropdown (lower right one)](https://brandwatch-axiom-tomru.netlify.com/docs/packages/axiom-components/dropdown)
> Adding EllipsisTooltip

- packages/axiom-components/src/Context/ContextMenuItem.js
- packages/axiom-components/src/Context/__snapshots__/ContextMenu.test.js.snap
- packages/axiom-components/src/Context/__snapshots__/ContextMenuItem.test.js.snap
A [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1084196) in firefox cause mouse events to not fire below a button element causing the EllipseTooltip to not work inside a DropdownContextMenuItem in Firefox.
Generally it makes sense to use a button for a ContextMenuItem as long as it is a simple entry you can click.
But there are at least two use-cases that allow some sort of interaction inside the ContextMenuItem:
1. checkbox to activate ContextMenuItem
2. showing a tooltip on a truncated named (using the EllipseTooltip)
Though the definition of the button does [permit interactive content](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button).
As there are use-cases where there is interaction in the ContextMenuItem it is reasonable to change the element of ContextMenuItem …
> fix(ContextMenuItem): mouse events do not fire in firefox

- packages/axiom-components/src/Context/ContextMenuItem.js
- packages/axiom-components/src/Context/__snapshots__/ContextMenu.test.js.snap
- packages/axiom-components/src/Context/__snapshots__/ContextMenuItem.test.js.snap
This reverts commit 7590b94de13e911ccae7480e1dded81086a79311.
https://github.com/BrandwatchLtd/axiom/pull/705 had a knock on effect on `ContextMenuItem` when used directly which I missed.
The applied change causes the highlight to not work anymore and shows a cursor instead of a pointer.
Reverting for now until we find a better solution
> fix(ContextMenuItem): revert "mouse events do not fire in firefox"

- packages/axiom-components/src/Context/Context.css
In https://github.com/BrandwatchLtd/axiom-react/pull/704 we added  `overflow-x: hidden` which unexpectetly causes `overflow-y` to compute to `auto` ( see note on [here](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-y) ) causing scroll bars to show everywhere, where a `ContextMenuItem` have filled with more content that there was space available.
This PR will also set `overflow-y: hidden` to guard against scrollbars in these cases.
> fix(ContextMenuItem): hide all overflow, not only overflow-x

- packages/axiom-materials/src/colors.css
- packages/axiom-materials/src/colors.js
- site/components/Documentation/Resources/Materials/Colors.js
- site/components/Documentation/Resources/Materials/Colors/ColorGrid.css
This also adds a little but of positive feedback to click on a color to get the variable name in your clipboard
> docs: Add "Better Together" colour

- packages/axiom-components/src/Context/Context.css
- packages/axiom-components/src/Context/ContextMenuItem.js
- packages/axiom-components/src/Context/__snapshots__/ContextMenu.test.js.snap
- packages/axiom-components/src/Context/__snapshots__/ContextMenuItem.test.js.snap
- packages/axiom-components/src/Dropdown/DropdownMenuItem.js
- packages/axiom-components/src/Dropdown/__snapshots__/DropdownMenuItem.test.js.snap
This PR is adding a `paddingVertical` property to the `ContextMenuItem` component. The default will be set to `medium`. I'm only adding a `small` option as this is what we need. We can probably extend this as soon as other variations will be used as well.
I've changed `DropdownMenuItem` to contain `paddingVertical` in the `propTypes` so the option appears in the Documentation.
> Adding "paddingVertical" property to "ContextMenuItem"

- packages/axiom-components/src/Icon/Icon.js
- packages/axiom-components/src/Icon/Icon.test.js
- packages/axiom-components/src/Icon/__snapshots__/Icon.test.js.snap
Add the option to set the `height` and/or `width` instead of just `size` for an icon. 
Useful for non-square icons like the iris icon added in #726
> feat(Icon): add support for custom width/height

- packages/axiom-components/src/DurationPicker/DurationPicker.js
- packages/axiom-components/src/DurationPicker/__snapshots__/DurationPicker.test.js.snap
* Amends styling of Duration Picker (spacing issue wasn't apparent when testing in docs)
* Adds ability to pass props to child elements (invalid, size, etc)
> Duration Picker style + child props

- packages/axiom-components/package.json
- packages/axiom-components/src/DurationPicker/DurationPicker.js
- packages/axiom-formatting/package.json
- yarn.lock
Removed a workaround, as a result of Luxon being patched here https://github.com/moment/luxon/pull/470
> refactor: updates luxon and removes defunct workaround

- packages/axiom-components/src/Context/Context.css
- packages/axiom-components/src/Context/Context.js
- packages/axiom-components/src/Tip/Tip.css
- packages/axiom-components/src/Tip/Tip.js
- packages/axiom-components/src/Tooltip/TooltipContext.js
- site/components/Documentation/Resources/Components/Tooltip.js
https://office.brandwatch.com/jira/browse/AX-135
This PR addresses a few things to do with Tooltips
**Inaccurate Documentation**
The documentation for Tooltips had the `TooltipSource` component hard-coded to have the `theme='night'` prop, which is unrepresentative of how implementation of ToolTips may have occurred within other projects. This has been removed and now shows how Tooltips actually work if just used exactly as they appear.
I would propose in the new documentation that we write using DocZ that gotchas like this are covered in a possible `use cases` section, with explanations as to why you need to give `TooltipSource` a theme in the first place.
**Font Color**
After removing the hard-coded theme from the documentation, it was easier to see another issue that was hidden …
> AX-135 - Dark Tooltips

- package.json
- packages/axiom-components/src/DatePicker/DatePickerControls.js
- packages/axiom-components/src/Dropdown/Dropdown.js
- packages/axiom-components/src/Dropdown/DropdownContext.js
- packages/axiom-components/src/Dropdown/DropdownMenuItem.js
- packages/axiom-components/src/Dropdown/DropdownReactContext.js
- packages/axiom-components/src/Dropdown/DropdownSource.js
- packages/axiom-components/src/Dropdown/DropdownTarget.js
- packages/axiom-components/src/Select/SelectInput.js
- yarn.lock
Legacy context API has a bug, was never probably supported and has performance issues. We use this API in several components the upgrade is pretty simple but this PR just deals with the Dropdown component. I will update the rest of the components using the same pattern in a 2nd PR.
Further Reading.
reactjs.org/docs/legacy-context.html
https://kentcdodds.com/blog/migrating-to-reacts-new-context-api
>  chore(Dropdown): Update Dropdown components to use new context API.

- packages/axiom-components/src/Slider/Handle.js
- packages/axiom-components/src/Slider/Range.js
- packages/axiom-components/src/Slider/Range.test.js
- packages/axiom-components/src/Slider/Slider.js
- packages/axiom-components/src/Slider/__snapshots__/Handle.test.js.snap
- packages/axiom-components/src/Slider/__snapshots__/Range.test.js.snap
- packages/axiom-components/src/Slider/__snapshots__/Slider.test.js.snap
This PR fixes four bugs from the initial implementation.
The first bug is where when the two handles were on the same values it was impossible to pick and move the upper handle any more.
The second bug is where the `values` prop was being mutated resulting in the state of the wrapping component being modified without calling `setState`.
The third bug is about the `withTooltip` option not being passed to the Handle component.
The fourth bug is about calculating the right position when `min` option is different from 0.
> fix(Slider/Range): set of fixes

- packages/axiom-components/src/Chip/Chip.css
- packages/axiom-components/src/Chip/Chip.js
- packages/axiom-components/src/Chip/ChipList.css
- packages/axiom-components/src/Chip/ChipList.js
- packages/axiom-components/src/index.js
- packages/axiom-materials/src/sizing.css
- site/components/Documentation/Resources/Components.js
- site/components/Documentation/Resources/Components/Chip.js
A new chip component, wrapped in a auto-collapsing chip list component.  This was originally used for AD-4010, the topics in the details view work.  
Some examples of the different options:
Some things to note:
- if there are not enough chips to have a multiline list, the list will not be collapsible
- you can use the `size` prop on both individual Chip components and the whole ChipList component.  The latter will apply the size to all Chips within the container.  
- if `activeColor` is not set, the default is 'accent' and solid.  However, if an `activeColor` is set, the Chip has a "outline" style, as per other use-cases.  
Preview [here](https://deploy-preview-740--serene-shannon-8198f2.netlify.com/docs/packages/axiom-components/chip)
> feat(Chip): Add chip component

- packages/axiom-components/src/Dialog/Dialog.js
This will allow modals to be kept open when clicking outside of the Dialog.
Default of true will mean the behaviour of existing Dialogs will not change.
> feat(Dialog): Add new prop "hasOverlay" to allow no overlay to be shown.

- packages/axiom-components/src/Dropdown/DropdownReactContext.js
This PR adds default values for the `DropdownReactContext`.
It follows https://github.com/BrandwatchLtd/axiom-react/pull/735 where the React context was being upgraded to use the newer context API.
In cases where the context was not initialised by a `Provider` (e.g. tests for Custom Dropdown components in Analytics), the `handleClick` function of `DropdownMenuItem` was failing because the context was undefined and it couldn't be destructured. https://github.com/BrandwatchLtd/axiom-react/pull/735/files#diff-aa76d52af9329b3bdab3323aa96f9233R38
> chore: add defaults context props

- packages/axiom-components/src/Form/TextInputIcon.js
- packages/axiom-components/src/Form/TextInputIcon.test.js
- packages/axiom-components/src/Form/__snapshots__/TextInputIcon.test.js.snap
- packages/axiom-components/src/Tooltip/TooltipContext.js
- site/components/Documentation/Resources/Components/Form.js
Sorry @lpoulter and @Binarytales, I should have checked with @Flawwles earlier on this. He wants us to be able to specify the colour for the tooltip, hence I've changed it to allow us to pass in the TooltipContext instead.
I'm not necessarily super keen on the `static typeRef` pattern to validate the type of the tooltip prop but have gone with it firstly for consistency, and secondly coz I couldn't get the other way to work for `TooltipContext`.
Have also added a tooltip to the example in the docs, happy to remove that if you want; the code's slightly gnarly as we're passing a React element as a prop; but I think it's worth showing how it's done.
> Textinput icon tooltip

- packages/axiom-components/src/Slider/Range.js
- packages/axiom-components/src/Slider/Range.test.js
- packages/axiom-components/src/Slider/__snapshots__/Range.test.js.snap
This PR fixes a bug where when the values were out of bound, the handles were being forcefully positioned at the boundaries but their internal values were kept out of bound, resulting on a miscalculation of the nearest handle.
Now the outbound values are reset to the boundaries on component creation so that the later calculation of the nearest handle is correct.
> fix(Range) ensure values are in bounds

- packages/axiom-components/src/Dialog/Dialog.js
- packages/axiom-components/src/Dialog/DialogBody.js
- packages/axiom-components/src/Dialog/DialogFooter.js
- packages/axiom-components/src/Dialog/DialogHeader.js
Allows a custom class to be passed to each of the 4 `Dialog` component.
This saves these sort of `shenanigans`
```
<div className="apply-some-sweet-sweet-layout">
<DialogBody>...</DialogBody>
</div>
```
> feat(Dialog): Add classname prop to Dialog components

- packages/axiom-components/src/DatePicker/DatePicker.js
- packages/axiom-components/src/DatePicker/DatePickerContext.js
- packages/axiom-components/src/DatePicker/DatePickerSelection.js
In https://github.com/BrandwatchLtd/axiom-react/pull/614 `initialDate` was missed to be passed down to the new `DatePickerSelection`.
With `initialDate` you can define which month should be shown, when a user opens the dialog, without setting any date/date range as selected. So IMO it's still useful and should be kept.
This PR fixes `initialDate` to work again.
> fix(DatePicker): pass on initialDate prop

- packages/axiom-components/src/Form/InputWrapper.css
- packages/axiom-components/src/Form/InputWrapper.js
- site/components/Documentation/Resources/Components/Form.js
Fix the label hint margin when inline. 
Preview [here](https://deploy-preview-758--serene-shannon-8198f2.netlify.com/docs/packages/axiom-components/form)
> fix(InputWrapper): Apply margin to hint when label is inline

- packages/axiom-components/src/Position/Position.css
I've improved the position of the Dropdown component when using `showArrow` and `offset`. I've noticed the dropdown is a little misplaced:
When inspecting you can see it has a margin applied on every side:
I've updated the CSS to only apply the margin on the side where the arrow is being shown, resulting in this:
> fix(Position): Fixes the margin depending on where the arrow is shown

- packages/axiom-materials/src/colors.js
When the UICarbon color was updated by Harry (#491) he only updated the CSS file and missed the JS.
This will bring the UICarbon color inline with the CSS file and also the color used across the Sketch file.
> fix(color): Fix uiCarbon color

- packages/axiom-components/src/Card/Card.js
- packages/axiom-components/src/Card/CardCaption.js
- packages/axiom-components/src/Card/CardContent.js
- packages/axiom-components/src/Card/CardImage.js
- packages/axiom-components/src/Card/CardImages.js
- packages/axiom-components/src/Card/CardList.js
Allows a custom class to be passed to Card Components.
This means that
```javascript
<div className="dialog__sidebar">
<CardList>...</CardList>
</div>
// is Now
<CardList className="dialog__sidebar">...</CardList>
```
> feat(CardComponents): Add classname prop to all Card Components

- packages/axiom-components/src/Base/Base.js
- packages/axiom-components/src/Form/TextInput.js
Currently it is only allowed to pass in objects, but in certain cases a function is needed as a ref prop (see https://reactjs.org/docs/hooks-faq.html#how-can-i-measure-a-dom-node for more details/examples)
> fix: Allow functions as ref props

- packages/axiom-components/src/Slider/Range.js
- packages/axiom-components/src/Slider/Range.test.js
The code ensuring that the handles were not crossing over was only called on mousemove but it also needs to be called on mouseup.
> fix(Range): range sliders crossing over on mouse up

- packages/axiom-components/src/Form/TextInput.js
`TextInput` takes a `space` property, but does not pass it on correctly to the `InputWrapper`. E.g.
```jsx
<TextInput space="x0">
<TextInputIcon align="left" name="magnify-glass" />
<TextInputButton>Search</TextInputButton>
</TextInput>
```
will still use `x4` on the on an internal element (`ax-input__wrapper`).  [Example](https://codesandbox.io/embed/green-firefly-z5q8q)
The issue is not visible when you don't add multiple children to the `TextInput` like in the example as the last child does never have a bottom margin.
This PR fixes this issue.
> fix(TextInput): respect space prop on TextInput with multiple children

- packages/axiom-components/src/Dropdown/DropdownContext.js
In our New Relic project, we see many errors regarding to `Cannot read property 'contains' of undefined`. I was able to track it down to this component where a null check was missing in case `dropdownRef()` returns `null`.
> fix(DropdownContext): ensure ref value is not null

- packages/axiom-materials/src/colors.js
I used the over version by mistake.
> fix(colors): Use correct Crash course for brand color

- scripts/publish_packages.sh
Hardcode the registry we currently publish to, so e.g. a local `~/.npmrc` does defined where the packages are published.
> chore(publishing): hard code registry

- scripts/process_flags/lib/palette.js
It looks like Facebook's brand change messed up our flags. The two should not be related but Axiom doesn't have a navy blue in the palette, so I've had to switch to Tumblr for now. Let's hope they don't rebrand…
Ideally I would like to make the colour matching smarter and prioritise hue over the full colour value, but this is a quick and easy fix.
> Flag color fix

- packages/axiom-components/src/DatePicker/DatePickerContext.js
Brought up by @bwSpiceBall in the Axiom Clinic.
> fix(DatePickerContext): the date range label shows the correct start date

- packages/axiom-components/src/Icon/Animicon.css
- packages/axiom-materials/src/icon_svgs/cross.svg
The cross icon has been created with two paths, this is to enable the animicon component to animate each path separately.
Because we created the cross with two overlapping paths, it means any time we used the cross icon with opacity, you saw the overlap..
Look at overlapping parts of the cross 🕵️‍♂️
This PR changes the animation of the cross, but I dont think its used much if at all?
This might not be the best solution, but hopefully we can get the ball rolling with this.
> fix(animicon): Changed Cross animation

- packages/axiom-components/src/AlertDropdown/AlertDropdownSource.js
- packages/axiom-components/src/Avatar/Candytar.js
- packages/axiom-components/src/Dropdown/DropdownContext.js
- packages/axiom-components/src/Editable/EditableLine.js
- packages/axiom-components/src/Image/ImageFallback.js
- packages/axiom-components/src/Portal/Portal.js
- packages/axiom-components/src/Progress/ProgressFinite.js
- packages/axiom-components/src/Progress/ProgressInfinite.js
- packages/axiom-components/src/Reveal/Reveal.js
- packages/axiom-components/src/Tabset/Tabset.js
- packages/axiom-components/src/Transition/Transition.js
- packages/axiom-components/src/Validation/Validate.js
- packages/axiom-documentation-viewer/src/DocumentationApi.js
Since the [release](https://reactjs.org/blog/2019/08/08/react-v16.9.0.html#new-deprecations) of react 16.9, anyone using a carat matcher in their package.json will have started getting console warnings for using deprecated lifecycle methods.
I'd actually argue that these lifecycles should be rewritten using non-deprecated lifecycles. But this is at least a first step to prevent console warning's in everyone's project using axiom-react.
> chore: rename unsafe lifecycles

- packages/axiom-components/src/EllipsisTooltip/EllipsisTooltip.js
Based on https://github.com/BrandwatchLtd/axiom-react/pull/738, I'm adding the `color` prop to the `TooltipContext` for `EllipsisTooltip`. This enables you to change the background between carbon and white.
> NOTICKET Add color prop to EllipsisTooltip

- packages/axiom-components/src/Context/Context.css
Small change to the hover colour of the Dropdown & Select boxes.
> feat(Dropdown/Select): Changed selected color to grey

- packages/axiom-components/src/Icon/Icon.js
- packages/axiom-materials/src/icon_svgs/drag.svg
- packages/axiom-materials/src/icons.js
To be able to reorder a list by drag and drop we need a drag handle. 
Adding the icon provided by @lilybrandwatch in this PR
> feat(Icon): add drag handle icon

- packages/axiom-components/src/Progress/ProgressButton.css
With ProgressButton, because we have an extra wrapper for the content that isn't flexed, adding items such as ButtonIcons means that they aren't centred (causing the button to render larger as well)
this fixes that:
> feat(ProgressButton): added flex to content wrapper

- packages/axiom-components/src/Form/TextInput.js
- packages/axiom-components/src/Form/TextInput.test.js
- packages/axiom-components/src/Form/__snapshots__/TextInput.test.js.snap
Currently using the `TextInputIcon` **with** the `onClear` property on `TextInput` isn't possible.
This PR is removing this limitation. As a result **if** someone wrote code as follows:
```js
<TextInput onClear={ () => {} }>
<TextInputIcon name="magnify-glass" />
</TextInput>
```
this would result in the input looking like this:
The code can be fixed by explicitly passing the `align` property to `TextInputIcon` with a value of `left`:
```js
<TextInput onClear={ () => {} }>
<TextInputIcon name="magnify-glass" align="left" />
</TextInput>
```
As a result the input is going to look like this:
**As the combination of `onClear` and `TextInputIcon` isn't possible at the moment I don't expect anyone to be affect **but** just to be on the safe side I made this a breaking change. There won't be …
> feat(TextInput): Removed condition preventing "clear" icon AND input icon

- packages/axiom-components/src/Avatar/Candytar.css
- packages/axiom-components/src/Avatar/Candytar.js
- packages/axiom-composites/src/UserMenu/UserMenu.js
- site/components/Documentation/Resources/Components/Avatar.js
This PR does the following:
- Updates the Candytar component to accept and show the User's initials. If no initials are supplied then it shows the silhouette by default.
- Updates the UserMenu component to use the initials prop for the Candytar component so the User's initials are shown.
- Adds the initials prop to two of the Candytar components in the Avatar documentation example.
> MYB-2 update user avatar

- README.md
Changing the readme file to help someone who hasn't installed Axiom before and give them a quick example to get them started. 
Happy to hear any suggestions on how to improve this.
> docs(readme): Add getting started

- packages/axiom-components/src/Dialog/Dialog.css
- packages/axiom-components/src/Dialog/Dialog.js
- packages/axiom-components/src/Modal/Modal.js
- site/components/Documentation/Resources/Components/Dialog.js
Add size prop with 2 options to allow dialog to cover w…hole screen and cover with padding.
BREAKING CHANGE: Usage of the fullscreen property on the Dialog component will now have no effect. You can recreate the previous fullscreen mode by passing `size=large` e.g.
```
<Dialog size="large" />
```
Size fullscreen will remove the padding previously found in fullscreen mode.
large size
fullscreen size
> feat(Dialog): Adds new large and fullscreen options.

- packages/axiom-components/src/Form/InputWrapper.js
- packages/axiom-components/src/Form/TextInput.js
This is adding a `labelSpace` property to the `TextInput` component so you can customize the margin between the Label and the Input.
It provides any of the `x0-8` options. Currently it is hard-coded to `x2`.
Note: If `inlineLabel` is set we do not provide this option.
> feat(TextInput): Adding a "labelSpace" property

- packages/axiom-components/src/Separator/Separator.js
- packages/axiom-components/src/Separator/Separator.test.js
- packages/axiom-components/src/Separator/__snapshots__/Separator.test.js.snap
Allows the `Separator` component to use `className` prop.
I currently have a situation where I have the following: 
But need this:
Where the separator color changes based on parent's focused state. I could override the ax class but felt like a class on the separator itself was cleaner.
> feat(Separator): allow className prop

- packages/axiom-components/src/Validation/InlineValidation.js
This enables the arrow on the `Tooltip` in the `InlineValidation` component. The default for this property is `false` to stay backwards-compatible without a breaking change.
> feat(Validation): Add "showArrow" property to InlineValidation component

- packages/axiom-components/package.json
- yarn.lock
Popper was updated to a 1.12.9 in a recent axiom update which causes issues where, on a small window, opening up a dropdown (or trying to) could completely freeze the browser tab and make it unresponsive
You can replicate the bug in the documentation site by shrinking the window down, opening up a Dropdown and scrolling up and down (doesn’t happen 100% of the time so keep trying)
> fix: fix issue where popper would completely freeze the browser tab

- packages/axiom-composites/src/ChangePasswordDialog/ChangePasswordDialog.js
- packages/axiom-composites/src/FormInputs/ConfirmPasswordInput.js
- packages/axiom-composites/src/FormInputs/CurrentPasswordInput.js
- packages/axiom-composites/src/FormInputs/NewPasswordInput.js
This reverts commit d6c6067
Looks like I changed a base api component thinking it was just and example used in the docs. 🤪
ChangePasswordDialog is used in accounts.brandwatch and my brandwatch this change was breaking them when they updated axiom.
> Revert "fix(Validate): Update docs example to use a dymanic required"

- packages/axiom-components/src/Avatar/Candytar.js
The candytar had alignment issues with the initials when viewed in Firefox. 
Before (Firefox)
After (Firefox)
After (Chrome)
> fix(Candytar): Initials baseline alignment

- packages/axiom-components/src/Avatar/Candytar.js
The PR is to implement a well supported way to align the Initials in the Candytar component.
I have tested on the latest versions of Chrome, Firefox and Safari only, so more QA may be needed.
> fix(Candytar) baseline alignment for initials

- packages/axiom-components/src/Form/ChedioButtox.css
- site/components/Documentation/Resources/Components/Form.js
Setting the position to absolute caused a bug when the window was scrolled.
The browser would jump the scroll position to compensate for the difference between the absolutely positioned native element at the top of the page and the Axiom custom checkbox.
Example of bug [here](https://zfrfg.csb.app/)
> fix(checkbox): Browser jump when scrolled. 

- packages/axiom-components/package.json
- packages/axiom-formatting/package.json
- packages/axiom-formatting/src/formatDate.js
- packages/axiom-formatting/src/formatDate.test.js
- yarn.lock
In Chrome 80, there was a bug (either in Chrome or Luxon) that caused constructed dates to move forwards by 24 hours which was causing big issues for Vizia. We've updated on our side of things but here's a safety fix.
https://github.com/moment/luxon/issues/619
> fix: updates luxon to fix chrome 80 bug

- packages/axiom-components/src/Button/Button.stories.js
- packages/axiom-utils/src/findComponent.js
- packages/axiomDocs.stories.mdx
Whilst working on the Dropdown Stories I noticed findComponent was unable to find Dropdown Target and the other nested components. This is because storybook wraps all components when rendering them. I've added a condition that will check if the outer component is a Storybook element and check one level deeper if it is.
> Storybook config

- packages/axiom-components/src/Dropdown/Dropdown.stories.js
- packages/axiom-components/src/Dropdown/Dropdown.stories.mdx
Adds Storybook docs for the Dropdown Component.
Storybook has a [bug currently](https://github.com/storybookjs/storybook/issues/9583). The code preview of the story imported to the mdx file is not correct.
Note we are still using @next of Storybook as we await 6.x.
Also for now can focus on creating documentation example and content and aim to add more design and polish later.
> Adds Storybook docs for the Dropdown Component.

- packages/axiom-components/src/Dropdown/DropdownContext.js
- packages/axiom-components/src/Portal/Portal.js
- packages/axiom-components/src/Progress/Progress.stories.js
- packages/axiom-components/src/Progress/ProgressFinite.js
- packages/axiom-components/src/Progress/ProgressInfinite.js
- packages/axiom-components/src/Validation/Validate.js
- packages/axiom-documentation-viewer/src/DocumentationApi.js
`componentWillMount` is now marked as legacy and will be dropped completely in React 17. 
There is no direct replacement. `componentWillMount` methods will be moved to either the constructor or `componentDidMount` depending if they need to happen before or after first `render`.
> Remove unsafe componentWillMount

- packages/axiom-components/src/Button/Button.js
- packages/axiom-components/src/Button/Button.stories.js
- packages/axiom-components/src/Button/Button.test.js
- packages/axiom-components/src/Button/__snapshots__/Button.test.js.snap
- packages/axiom-components/src/DatePicker/DatePickerControls.js
- packages/axiom-components/src/DatePicker/DatePickerHeaderControl.js
- packages/axiom-components/src/Dialog/Dialog.stories.js
- packages/axiom-components/src/Dropdown/Dropdown.stories.js
- packages/axiom-components/src/Icon/IconButton.js
- packages/axiom-components/src/Pagination/PaginationButton.js
- packages/axiom-components/src/Progress/ProgressButton.js
- packages/axiom-components/src/Tooltip/Tooltip.stories.js
- packages/axiom-components/src/Transition/Transition.stories.js
- packages/axiom-composites/src/ChangePasswordDialog/ChangePasswordDialog.js
Style is a key word in JSX often used to apply inline styles. It's use causes confusion and linter warnings. Here we replace with variant. Codemod [here](https://www.npmjs.com/package/axiom-codemods).
BREAKING CHANGE: 🧨
`<Button style="primary">` becomes `<Button variant="primary">`
Please use `npx axiom-codemods rename-button-style-attribute <path>` to replace in your code.
> AX-203: Rename Button attribute style => variant 

- .github/workflows/build.yml
Restores PR preview builds. 
We push the built Storybook files to Netlify to avoid the need to build twice as we previously did. Also by building on gh actions we don't use the limited netlify build minutes.
Uses [actions-netlify](https://github.com/nwtgck/actions-netlify)
> ci: 🎡 Deploy to Netlify action

- package.json
The last publish only included the ESM files. Adding this npm script bug
in to trigger a fix build.
> fix: 🐛 Build both cjs/esm packages for publishing

- packages/axiom-components/src/Context/__snapshots__/ContextMenuItem.test.js.snap
- packages/axiom-components/src/Form/Tick.js
- packages/axiom-components/src/Form/__snapshots__/CheckBox.test.js.snap
- packages/axiom-components/src/Form/__snapshots__/CheckBoxGroup.test.js.snap
There was a bug in storybook that reset the border box on elements. This caused the checkbox to be correctly centred. When the storybook bug was fixed the check box broke.
The height of the checkbox and SVG are both now 14 + border 1 + border 1 = 16px/1rem
> fix(CheckBox): Account for element border-box in svg sizing

- packages/axiom-components/src/Form/ChedioButtox.css
Closes #912 
This can result in the undesirable side-effect of toggling of the
checkbox or selecting the text if the use clicks fast. However after testing out a few options I feel
that text selection worth the cost and feels a better default.
> feat: 🎸 Checkbox & Radio Buttons, make label text selectable

- packages/axiom-components/src/EllipsisTooltip/EllipsisTooltip.js
- packages/axiom-components/src/Table/Table.css
- packages/axiom-components/src/Table/Table.stories.js
- packages/axiom-components/src/Table/TableHeaderLabel.js
- packages/axiom-components/src/Table/TableHeaderLabel.test.js
- packages/axiom-components/src/Table/__snapshots__/TableHeader.test.js.snap
- packages/axiom-components/src/Table/__snapshots__/TableHeaderLabel.test.js.snap
This PR allows us to have wrappable table headers. After consultation with @Flawwles, it was decided to limit the number of possible lines to 2.
As noted in the commit message, to achieve this I've used the `line-clamp` property.
> Word wrap table headers

- packages/axiom-components/src/Slider/Range.js
- packages/axiom-components/src/Slider/Range.test.js
- packages/axiom-components/src/Slider/__snapshots__/Range.test.js.snap
[![SN-242](https://badgen.net/badge/JIRA/SN-242/0052CC)](https://office.brandwatch.com/jira/browse/SN-242) 
By ensuring values are in within the bounds of the Range slider, we did not take care of edge cases like for example when `min` and `max` have infinite values (the min and max bounds are sometimes set dynamically). This resulted in the new values being set to `NaN` which in turn was disabling the Range slider when `min` and `max` bounds were reset to finite numbers.
This PR fixes this undesired behaviour by not adjusting the slider values when the new values would not be finite (NaN for example).
> fix: keep original values if transformed values or step not finite

- packages/axiom-components/src/UsageHint/UsageHint.js
I noticed that the UsageHint is effectively using the Icon component (which accepts the inline prop) but doesn't support the inline prop. This is something that we could use in the QueryBuilder to inline the UsageHint with the text (can also be done with Grid, but thought this is nicer).
> NOTICKET Enable inlining UsageHint

- packages/axiom-components/src/Context/__snapshots__/ContextMenuItem.test.js.snap
- packages/axiom-components/src/Form/CheckBox.stories.js
- packages/axiom-components/src/Form/ChedioButtox.css
- packages/axiom-components/src/Form/ChedioButtox.js
- packages/axiom-components/src/Form/Indeterminate.js
- packages/axiom-components/src/Form/Tick.js
- packages/axiom-components/src/Form/__snapshots__/CheckBox.test.js.snap
- packages/axiom-components/src/Form/__snapshots__/CheckBoxGroup.test.js.snap
Fixes #925 
When making the tick mark an SVG i broke the disabled styles this PR fixed that.
Un-Checked Disabled
Checked Disabled 
Indeterminate
Indeterminate - disabled
Indeterminate - invalid
> fix: Checkbox disabled/indeterminate states

- packages/axiom-components/src/Button/Button.stories.js
- packages/axiom-components/src/Progress/ProgressButton.js
I like progress buttons. (https://github.com/BrandwatchLtd/axiom-react/pull/935)
Since Progress already accepts a color prop of subtle (was using white which matched primary well) I thought I'd add support for the ProgressButton to be secondary as well. Wouldn't really make sense to enable other variants as they essentially don't have backgrounds.
Let me know what you think.
> style: 💄 Adds secondary style to ProgressButton

- .storybook/preview.js
- packages/axiom-components/src/Form/TextInput.js
- packages/axiom-components/src/Form/TextInput.stories.js
- packages/customisingAxiom.stories.mdx
Implements a new pattern as discussed in #919. In future where we have elements with multiple children we might want to pass a classname to we will use a custom prob see `inputClassName` as an example. I also documented this pattern in the docs in a new "Customising Axiom" section.
- Pass ClassName to TextInput
- Add new prop to pass class to input element
- Add new docs section "Customising Axiom"
> Text input classname

- packages/axiom-components/src/Tabset/Tab.stories.js
- packages/axiom-components/src/Tabset/Tabset.css
- packages/axiom-components/src/Tabset/Tabset.stories.js
Adds stories for Tab/Tabs closing #929 
Use Title-case for tab titles, see design docs https://gallery.io/projects/MCHbtQVoQ2HCZWJoeSrzl9FQ/files/MCEJu8Y2hyDScV7ZDNnEvUAFDwjpqSh7JR4
> fix: Change Tab titles to be title-case to match design docs

- packages/axiom-components/src/Editable/Editable.stories.js
- packages/axiom-components/src/Editable/EditableLine.js
This PR changes the `EditableLine` from holding local state, to passing through the `onChange` handler and `value` property to the input.
**BREAKING CHANGE:** onChange of the `EditableLine` component is called on every change to the input now and receives the original event as an argument
---
Previously the `onChange` handler was only called on blur, if the value has changed. This caused an issue, where the value was reseted if the component was re-rendered while editing, before the blur event.
The issue can be produced in [this code sandbox](https://codesandbox.io/s/axiom-editable-line-issue-4j7fl).
> fix(EditableLine): Call onChange on every change

- packages/axiom-components/src/Icon/Icon.js
- packages/axiom-components/src/Icon/iconNames.js
- packages/axiom-materials/src/icon_svgs/arrow-left.svg
- packages/axiom-materials/src/icon_svgs/arrow-right.svg
- packages/axiom-materials/src/icons.js
We were missing the arrow left icon which is being used in a few upcoming designs. To complete the set, I also added the arrow right, which doesn't have an immediate use, but made sense to add at the same time.
> feat(Icons): Add arrow left and right

- packages/axiom-components/src/Editable/Editable.stories.js
- packages/axiom-components/src/Editable/EditableLine.css
- packages/axiom-components/src/Editable/EditableLine.js
#951 Added a change that removed `value` from the input, which seemed to break things for two reasons:
1. The value was ignored on the input
2. The `ax-editable-line__structure` element represented a different string, so the layout was broken
I've added this back in, and added a minimum width (of ~1 character), to make the hit-area more usable.
See sandbox for bug reproduction: https://codesandbox.io/s/axiom-boilerplate-forked-283h2?file=/src/components/App/index.js
It may not have been picked up because the storybook example had a similar string for both the value and placeholder, so the bug could have been missed in development.
cc @lpoulter @josa42
> fix: editable text sets value on input, adds minimum width for hit area

- packages/axiom-components/src/Button/Button.js
- packages/axiom-components/src/Button/ButtonGroup.js
- packages/axiom-components/src/Progress/ProgressButton.js
No need to replace just pass 'joined' prop to children of ButtonGroup
> refactor: 💡 Remove old context API from Button & ButtonGroup

- packages/axiom-components/src/AlertDialog/AlertDialog.js
- packages/axiom-components/src/AlertDialog/AlertDialogContext.js
- packages/axiom-components/src/AlertDialog/AlertDialogHeader.js
This api is due to be removed and it's use will cause problems in
coming versions of React. Also converted to functional components to make use of hooks
> refactor: 💡 Remove old context API from AlertDialog 

- packages/axiom-components/src/Form/TextInput.css
Currently the `TextInput` which has `invalid={true}` and is focused, shows a blue border and normal text color.
This PR makes sure the error color is used, even if the input is focused.
> fix(TextInput): Use error colors for invalid states, even if focused

- packages/axiom-components/src/Dialog/Dialog.js
- packages/axiom-components/src/Dialog/DialogContext.js
- packages/axiom-components/src/Dialog/DialogHeader.js
This PR superseeds #965, thanks to @josa42 for raising this bug and putting in a fix. 
The previous method of using DisplayName to clone in onRequest close to
the dialog header didn't work in production because displayName was
getting removed in the build process, not sure by what. Using context
should be more reliable and also have the benefit of allowing dialog
header to be wrapped in other elements. A trade of here is Dialogheader 
cannot be used outside of Dialog but I don't see this a problem in this case.
> fix: 🐛 Ensure onRequestClose is passed to dialog header

- packages/axiom-components/src/Position/Position.js
- packages/axiom-components/src/Position/Position.stories.css
- packages/axiom-components/src/Position/Position.stories.js
- packages/axiom-components/src/Slider/__snapshots__/Handle.test.js.snap
This will allow setting and overriding of Popper modifiers via the Axiom Position component. Other components that spread props to Position such as Dropdown and Tooltip will also support this feature.
Closes #985
> feat: 🎸 Pass Popper Modifiers to Position

- packages/axiom-components/src/Table/Table.css
In #923 a change was added to enable multi-line table header cells. I came across an issue where this didn't work. After some digging it turned out CSS for `.ax-text--ellipsis` was applied *after* the CSS for `TableHeader` was applied. This caused the CSS for `ax-table__header-tooltip--wrap` to be overwritten: More specifically the `white-space: nowrap;` was applied.
https://github.com/BrandwatchLtd/axiom-react/blob/4ae7091507289fa76ebf1dc075ad7a8c7915c806/packages/axiom-components/src/Typography/Text.css#L73-L78
https://github.com/BrandwatchLtd/axiom-react/blob/5c6de061f22bee6f27fecd8e912a1a27dedfca9e/packages/axiom-components/src/Table/Table.css#L163-L168
The easiest fix seems to be to increase the CSS selector specificity to give it more weight so the order of import doesn't matter. …
> fix: Increase specificity for table header wrapping

- packages/axiom-charts/src/DataPoint/DataPoint.js
- packages/axiom-charts/src/Line/LinePoint.js
- packages/axiom-components/src/Button/Button.js
- packages/axiom-components/src/Button/ButtonIcon.js
- packages/axiom-components/src/Card/Card.js
- packages/axiom-components/src/Dropdown/DropdownMenuItem.js
- packages/axiom-components/src/Form/TextInput.js
- packages/axiom-components/src/Icon/Icon.js
- packages/axiom-components/src/Image/Image.js
- packages/axiom-components/src/Label/LabelIcon.js
- packages/axiom-components/src/Reveal/Reveal.js
- packages/axiom-components/src/Select/SelectInput.js
- packages/axiom-components/src/Tooltip/Tooltip.js
- packages/axiom-components/src/Tooltip/TooltipTarget.js
These properties are only internal for internal use and should not be documented.
Skip was left over from the old docs and did not work with storybook.
Before.
After
> docs: ✏️ Correctly ignore probs with JSdocs and storybook

- packages/axiom-components/src/Table/Table.stories.js
- packages/axiom-components/src/Tabset/Tabset.css
- packages/axiom-components/src/Tabset/Tabset.stories.js
To bring inline with original designs
> fix: 🐛 Update unselected tab text color to be subtle

- packages/axiom-components/src/Tabset/Tab.stories.js
- packages/axiom-components/src/Tabset/Tabset.css
- packages/axiom-components/src/Tabset/Tabset.js
Updated to match our [new copy guidelines](https://gallery.io/projects/MCHbtQVoQ2HCZWJoeSrzl9FQ/files/MCEJu8Y2hyDScS4WA3eOZHqwVJrDBGgTc1w).
Before
After
> fix: 🐛 Only captalise the first letter of the first word. 

- packages/axiom-components/src/UsageHint/UsageHint.js
This PR does two things: 
- adds an information circle icon as a possible icon for UsageHint
- passes padding to `DropdownContent`, which enables us to have a smaller padding, the current default is `large`, which is imo too big and I'd like the option to change it flexibly
If you have a reason as to why the `information-circle` isn't suitable for a `UsageHint`, I'm fine with it. But I would really like if we could have more flexible paddings on `UsageHint`, since the logic is essentially there, and if the `UsageHint` does not contain a lot of text it looks weird.
> CP-563 Add Tooltip & HC link in the query builder

- packages/axiom-components/src/DurationPicker/DurationPicker.js
if days is not excludes then the selected unit by default will be days
days is often the most supported unit of time. This is particularly
useful in Vizia where we want to update a number of components at once
but not all support mins/hours etc. only day. We do not want to exclude
these other options as they are still valid for a subset of the components
We have the case at the moment in Deck Level Filters that I want to have no numeric value, but default the time unit to days.
I want this because the default numeric value might be different than the current values of some of the components - which would lead to an update without the user intending to do so.
I want to a a nicety have the default time unit to be days as this is the most supported time unit across our components in Vizia. …
> feat: default duration picker selected unit to days if valid

- packages/axiom-components/src/DurationPicker/DurationPicker.js
when the default selected value is passed in as an empty string/undefined
the duration picker does not save the default selected unit to state.
here we make sure we init the selected unit properly in state even if the
numeric value is undefined.
Without this pr the user has to reselect the unit from dropdown to get a valid duration (if the component is initialised with a blank/undefined value).
I have been able to reproduce this functionality locally on storybook.
- change the story book component for DurationPicker to not set an inital state (eg: `useState('')`)
- run story book, select duration picker.
- set a numeric value (eg: `7` in the input box)
- view that the duration printed underneath the component is undefined.
- checkout branch
- go through same steps and view that the …
> fix: default selected duration unit when empty selected value

- packages/axiom-components/src/Table/Table.css
- packages/axiom-components/src/Table/Table.stories.js
- packages/axiom-components/src/Table/TableHeaderLabel.js
- packages/axiom-components/src/Table/__snapshots__/TableHeader.test.js.snap
- packages/axiom-components/src/Table/__snapshots__/TableHeaderLabel.test.js.snap
Css selector for handling cursor and color for TableHeaderLabel was only checking `:disabled` pseudo class, but the pseudo class `:disabled` is only available for input elements. TableHeaderLabel is a div, and to make css selector target it, I also added the attribute selector to the css rule.
> fix: 🐛 Update css rule to handle disabled for TableHeaderLabel

- packages/axiom-components/src/Progress/Progress.js
- packages/axiom-components/src/Progress/ProgressFinite.js
- packages/axiom-components/src/Progress/ProgressInfinite.js
- packages/axiom-components/src/Progress/RadialProgress.css
- packages/axiom-components/src/Progress/RadialProgress.test.js
- packages/axiom-components/src/Progress/__snapshots__/RadialProgress.test.js.snap
adds a `tiny` option to the Progress components to match the AlertIcon sizes
> feat(axiom-components): add tiny option for progress components

- packages/axiom-components/src/UsageHint/UsageHint.js
Noticed while working on https://github.com/BrandwatchLtd/consumer-research/pull/1004 and thought I'd raise a PR. 
Icon already supports `spaceLeft` and `spaceRight`, this is just opening up those props to the `UsageHint` component.
> NOTICKET Allow usage of spaceLeft and spaceRight on UsageHint Icon

- packages/axiom-components/src/Form/TextInput.stories.js
- packages/axiom-materials/src/opacities.css
This PR improves the visibility of invalid TextInputs:
- Set opacity-input-border--invalid to 0.75
- Use warning-circle for invalid TextInputs
CC @Flawwles
> Update style of invalid TextInputs

- packages/axiom-components/src/Form/TextInputIcon.js
- packages/axiom-components/src/Form/TextInputIconWrapper.js
This PR update the TextInputIcon component to allow setting its color and use the dark style by default.
CC @Flawwles
> Use dark style tooltips for text input icons"

- packages/axiom-components/src/Table/Table.css
While experimenting with nesting tables I've stumbled over an issue when trying to set `horizontalPadding="none"` to a table cell, that did not work as expected.
See this [sandbox](https://codesandbox.io/s/axiom-tablecell-horizontalpadding-none-bug-sc5n0). This PR fixes the wrong usage of css properties for both the `none` case and `medium` case (which is the default anyways).
> fix(axiom-components): fix horizontalPadding in TableCell
