src/components/alert/Alert.js
src/components/alert/Alert.scss
src/components/alert/example/colors.js
src/components/alert/example/index.js
src/components/alert/example/removable.js
src/index.js
style-guide/constants/Examples.js

Alert component

---

src/components/alert/Alert.js
src/components/alert/Alert.scss
src/components/alert/example/icon.js
src/components/alert/example/index.js
src/components/alert/example/removable.js
src/components/dialog/__snapshots__/DialogHeader.test.js.snap
src/components/grid/Grid.js
src/components/grid/Grid.scss
src/components/grid/Grid.test.js
src/components/grid/__snapshots__/Grid.test.js.snap
src/components/icon/IconButton.scss
src/components/icon/IconIndicator.js
src/components/icon/IconIndicator.scss
src/components/icon/example/index.js
src/components/icon/example/indicator-colors.js
src/components/icon/example/indicator-sizes.js
src/index.js

IconIndicator

---

src/components/avatar/__snapshots__/Avatar.test.js.snap
src/components/image/Image.js
src/components/image/example/falling-back.js
src/components/image/example/index.js

Added an Image fallback pattern where if the image fails to load it renders it's children.

 Added Image fallback pattern

---

src/components/badge/Badge.js
src/components/badge/Badge.scss
src/components/badge/Badge.test.js
src/components/badge/__snapshots__/Badge.test.js.snap
src/components/badge/__snapshots__/BadgeGroup.test.js.snap
src/components/badge/example/group.js
src/components/badge/example/index.js
src/components/badge/example/opacity.js
src/components/base/Base.js
src/components/base/Base.scss
src/components/base/Base.test.js
src/components/base/__snapshots__/Base.test.js.snap
src/components/typography/example/colors.js

Extended Badge Colouring and Opacities

---

src/charts/wordcloud/Word.js
src/charts/wordcloud/__snapshots__/Word.test.js.snap
src/charts/wordcloud/example/data.js

Reverts BrandwatchLtd/axiom#119

Revert "Word cloud font fixes"

---

src/components/table/Table.js
src/components/table/Table.scss
src/components/table/Table.test.js
src/components/table/__snapshots__/Table.test.js.snap
src/components/table/example/h-gutters.js
src/components/table/example/index.js

This is my first Axiom PR! So if I've done anything wrong here or the commit message formatting is off please let me know! The change is required to meet design requirements for a table in Audiences. Thanks :D

feat(Table): add hGutters prop so horizontal gutters can be adjusted

---

src/components/table/TableCell.js
src/components/table/example/compact.js
src/components/table/example/grow.js
src/components/table/example/h-gutters.js
src/components/table/example/table.js

* Fixes TableCell propType warning. 
* Cleans up doc snippets
* Removes implicit default

Table corrections

---

src/charts/data-point/DataPoint.css
src/charts/data-point/DataPoint.js
src/charts/data-point/DataPoint.test.js
src/charts/data-point/DataPoints.js
src/charts/data-point/DataPoints.test.js
src/charts/data-point/__snapshots__/DataPoint.test.js.snap
src/charts/data-point/__snapshots__/DataPoints.test.js.snap
src/charts/data-point/example/data-point-colors.js
src/charts/data-point/example/data-points-grouped.js
src/charts/data-point/example/data-points-stacked.js
src/charts/data-point/example/index.js
src/index.js
style-guide/constants/Examples.js

feat(DataPoint): Adds DataPoint component

---

src/charts/wordcloud/Word.css
src/charts/wordcloud/Word.js
src/charts/wordcloud/WordCloud.js
src/charts/wordcloud/__snapshots__/Word.test.js.snap

Tested on:
IE11
Edge
Firefox
Chrome
Safari

feat(WordCloud): Adds basic animation

---

src/components/badge/BadgeGroup.css
src/components/button/ButtonGroup.css
src/components/grid/Grid.css
src/components/label/LabelGroup.css
src/components/reveal/Reveal.css
src/components/reveal/Reveal.js
src/components/reveal/example/index.js
src/components/reveal/example/reveal.js
src/index.js
style-guide/constants/Examples.js

_The animations are actually smoother than in the GIF_

feat(Reveal): Adds Reveal component

---

src/components/button/Button.css
src/components/button/Button.js
src/components/button/Button.test.js
src/components/button/__snapshots__/Button.test.js.snap
src/components/button/example/index.js
src/components/button/example/stadium.js
src/composites/pagination/Pagination.js
src/composites/pagination/Pagination.test.js
src/composites/pagination/PaginationButton.js
src/composites/pagination/PaginationButton.test.js
src/composites/pagination/PaginationButtonGroup.js
src/composites/pagination/__snapshots__/Pagination.test.js.snap
src/composites/pagination/__snapshots__/PaginationButton.test.js.snap
src/composites/pagination/example/base.js
src/composites/pagination/example/index.js
src/composites/pagination/utils.js
src/index.js
src/materials/number.test.js
style-guide/constants/Examples.js

feat(Pagination): Adds Pagination composite

---

src/components/progress/Progress.js
src/components/progress/ProgressFinite.js
src/components/progress/ProgressInfinite.js
src/components/progress/RadialProgress.css
src/components/progress/RadialProgress.js
src/components/progress/RadialProgress.test.js
src/components/progress/__snapshots__/Progress.test.js.snap
src/components/progress/__snapshots__/ProgressFinite.test.js.snap
src/components/progress/__snapshots__/ProgressInfinite.test.js.snap
src/components/progress/__snapshots__/RadialProgress.test.js.snap

Also I've flattened the structure a bit because there were some wrapping divs which didn't seem to be doing much that the SVG couldn't do, which meant we could move some more of the generic transform stuff up to `RadialProgress`

fix(Progress): By default horizontally align in the middle

---

.babelrc
package.json
src/components/alert/Alert.js
src/components/dialog/example/DialogDemo.js
src/components/dialog/example/fullscreen.js
src/components/dialog/example/sizes.js
src/components/dropdown/Dropdown.js
src/components/dropdown/DropdownMenuItem.js
src/components/dropdown/DropdownTarget.js
src/components/form/TextGroup.js
src/components/form/TextInput.js
src/components/image/ImageCircle.js
src/components/position/Position.js
src/components/reveal/example/reveal.js
src/components/tooltip/Tooltip.js
src/components/tooltip/TooltipTarget.js
src/composites/login/Login.js
src/composites/login/example/index.js
src/composites/pagination/Pagination.js
src/materials/example/numbers/long-number.js
src/materials/example/numbers/short-number.js
src/materials/example/numbers/tiny-number.js
style-guide/components/ApiDocs/ApiDocsDialogTrigger.js
style-guide/components/ApiDocs/ApiDocsProp.js
style-guide/components/Example/ExampleHeader.js
style-guide/components/Example/Snippet.js
style-guide/components/Layout/Layout.js
style-guide/components/Navigation/NavListItem.js
style-guide/containers/Navigation.js
yarn.lock

takes us from `babel-preset-stage-0` to `babel-preset-stage2`! 🎉

Remove experimental js

---

src/components/modal/Modal.css

fix(Dialog): Responsiveness

---

src/materials/colors.css

fix(Colors): Dark color adjustments

---

src/charts/bar-chart/Bar.css
src/charts/bar-chart/Bar.js
src/charts/bar-chart/Bar.test.js
src/charts/bar-chart/BarChart.css
src/charts/bar-chart/BarChart.js
src/charts/bar-chart/BarChart.test.js
src/charts/bar-chart/BarGroup.css
src/charts/bar-chart/BarGroup.js
src/charts/bar-chart/BarGroup.test.js
src/charts/bar-chart/__snapshots__/Bar.test.js.snap
src/charts/bar-chart/__snapshots__/BarChart.test.js.snap
src/charts/bar-chart/__snapshots__/BarGroup.test.js.snap
src/charts/bar-chart/example/BarChartTwoSeries.js
src/charts/bar-chart/example/BarChartTwoSeriesWithRatios.js
src/charts/bar-chart/example/barChartExampleSingleSeries.js
src/charts/bar-chart/example/data.js
src/charts/bar-chart/example/dataSingleSeries.js
src/charts/bar-chart/example/dataWithLabels.js
src/charts/bar-chart/example/index.js
src/index.js
style-guide/routes.js
webpack.static.config.js

Adds a new bar chart and supporting components.

feat(BarChart): Adds new Bar Chart type

---

src/charts/data-picker/DataPickerHeader.js
src/charts/data-picker/__snapshots__/DataPickerHeader.test.js.snap

fix(DataPicker): Fixes header display for small screens

---

webpack.static.config.js

Fixes #72 
js bundle down from 3mb to 1.2mb before gzip 🎉

chore(StyleGuide): minify js in styleguide build

---

src/charts/chart-axis/ChartAxisLabels.css
src/charts/chart-table/ChartTable.css
src/charts/chart-table/ChartTable.js
src/charts/chart-table/ChartTableAxis.js
src/charts/chart-table/ChartTableGrid.css
src/charts/chart-table/ChartTableRows.js
src/charts/chart-table/ChartTableRows.test.js
src/charts/chart-table/__snapshots__/ChartTableAxis.test.js.snap
src/charts/chart-table/__snapshots__/ChartTableRows.test.js.snap
src/charts/dot-plot/example/data.js
src/charts/dot-plot/example/dot-plot-table.js
src/charts/dot-plot/example/dot-plot.js

feat(chart-table): add expand/collapse functionality

---

package.json
src/components/base/Base.css
src/components/button/Button.css
src/components/form/TextArea.css
src/components/form/TextGroup.css
src/components/form/TextInput.css
src/components/typography/HorizontalRule.css
yarn.lock

Removed normalize.css due to issues with inserting Axiom into an existing application. Applied needed rules, some scoped to Axiom classes

fix(CSS): Removed normalize.css

---

src/charts/bars/Bar.css
src/charts/bars/Bars.css
src/charts/bars/example/data.js
src/charts/bars/vars.css

fix(Bars): Vertical percentage offset

---

src/charts/data-picker/__snapshots__/DataPickerMenu.test.js.snap
src/components/context/Context.css
src/components/context/Context.js
src/components/context/Context.test.js
src/components/context/__snapshots__/Context.test.js.snap
src/components/context/example/menu.js
src/components/context/example/tip.js

fix(Context): Give Context a max-height

---

src/charts/data-picker/DataPickerHeader.js
src/charts/data-picker/__snapshots__/DataPickerHeader.test.js.snap
src/charts/data-picker/example/changeable-color.js
src/charts/data-picker/example/data-picker.js
src/charts/data-picker/example/data.js
src/charts/data-picker/example/index.js
src/components/color-picker/ColorPicker.js
src/components/color-picker/ColorPickerOption.css
src/components/color-picker/ColorPickerOption.js
src/components/color-picker/ColorPickerOption.test.js
src/components/color-picker/__snapshots__/ColorPickerOption.test.js.snap

feat(DataPicker): Adds color picking ability

---

src/components/toolbar/Tool.js
src/components/toolbar/Tool.test.js
src/components/toolbar/Toolbar.js
src/components/toolbar/Toolbar.test.js
src/components/toolbar/__snapshots__/Tool.test.js.snap
src/components/toolbar/__snapshots__/Toolbar.test.js.snap
src/components/toolbar/example/base.js
src/components/toolbar/example/index.js
src/components/toolbar/example/tool.js
src/index.js
style-guide/routes.js
webpack.static.config.js

Try it out here: https://toolbar-component--philologist-boar-46686.netlify.com/docs/components/toolbar/

feat(Toolbar): Adds toolbar component

---

src/charts/data-point/DataPoints.js
src/charts/data-point/__snapshots__/DataPoints.test.js.snap
src/charts/dot-plot/DotPlot.js
src/charts/dot-plot/DotPlotChart.js
src/charts/dot-plot/DotPlotContext.js
src/charts/dot-plot/DotPlotDots.js
src/charts/dot-plot/__snapshots__/DotPlotChart.test.js.snap
src/charts/dot-plot/example/context.js
src/charts/dot-plot/example/index.js

feat(DotPlot): Support for Context

---

src/charts/data-picker/__snapshots__/DataPickerHeader.test.js.snap
src/components/color-picker/ColorPicker.js
src/components/color-picker/ColorPickerOption.css
src/components/color-picker/ColorPickerOption.js
src/components/color-picker/ColorPickerOption.test.js
src/components/color-picker/__snapshots__/ColorPickerOption.test.js.snap
src/components/color-picker/example/disabled.js
src/components/color-picker/example/index.js

feat(ColorPicker): Adds a disabled state to ColorPickerOptions

---

src/charts/data-picker/DataPicker.js
src/charts/data-picker/DataPicker.test.js
src/charts/data-picker/DataPickerHeader.css
src/charts/data-picker/DataPickerHeader.js
src/charts/data-picker/DataPickerHeader.test.js
src/charts/data-picker/__snapshots__/DataPicker.test.js.snap
src/charts/data-picker/__snapshots__/DataPickerHeader.test.js.snap
src/charts/data-picker/example/changeable-color.js
src/charts/data-picker/example/clearable.js
src/charts/data-picker/example/data-picker.js
src/charts/data-picker/example/index.js

BREAKING CHANGE:
* DataPicker component now controls all of the props of the component as opposed to DataPickHeader having props.
* `headerText` has been split into `value` and `placeholder` properties
* `isInvalid` is no longer needed and is derived from `value`
This breaking change was needed to provide DataPickHeader with a state where a value had been selected in order to show the CLEAR action.

feat(DataPicker): Adds clearable behaviour through `onClear` property

---

netlify.toml

This is actually all it takes to get going on netlify.
https://www.netlify.com
We would need to get the integration approved for BrandwatchLtd. From my understanding this will deploy PR's and branches. But we don't generally have branches as we generally fork the repo, It shouldn't deploy forked branches, but if people want to they can setup the integration themselves.
#110

chore(Netlify): Netlify config file

---

src/components/form/Toggle.css
src/components/form/Toggle.js
src/components/form/Toggle.test.js
src/components/form/__snapshots__/Toggle.test.js.snap
src/components/form/example/index.js
src/components/form/example/toggle.js
src/index.js
style-guide/routes.js

https://feat-toggle--axiom-rules.netlify.com/docs/components/form

feat(Toggle): Add Toggle component

---

src/charts/bar-chart/BarChart.js
src/charts/bar-chart/BarChartContext.js
src/charts/bar-chart/example/with-context.js

The labels were broken if you used React elements instead of strings - this should fix that!

Fix bar chart labels

---

src/components/form/Toggle.css
src/components/form/Toggle.js
src/components/form/Toggle.test.js
src/components/form/__snapshots__/Toggle.test.js.snap
src/components/form/example/toggle.js

feat(Toggle): Add clickable label next to switch via children

---

src/materials/date-and-time.js
src/materials/date-and-time.test.js
src/materials/example/date-and-time/filename-date.js
src/materials/example/date-and-time/index.js

feat(Date and Time): add filenameDate function

---

package.json
src/materials/date-and-time.js
src/materials/date-and-time.test.js
yarn.lock

The date functions were printing hours instead of minutes 🙀 ! This is fixed now and there are rudimentary unit tests too :D Also I have replaced moment with date-fns which significantly reduces build size 🎉

Fix date fns

---

src/charts/bar-chart/BarChart.css

[Netlify Deploy](https://benchmarking-design-tweak--hhogg-axiom.netlify.com/docs/charts/bar-chart)

fix(BarChart): Benchmarking bar design tweak

---

src/charts/bars/Bar.js
src/charts/bars/__snapshots__/Bar.test.js.snap
src/charts/bars/__snapshots__/Bars.test.js.snap
src/charts/bullet-chart/BulletBars.js
src/charts/bullet-chart/BulletBars.test.fixture.js
src/charts/bullet-chart/BulletBars.test.js
src/charts/bullet-chart/BulletChart.css
src/charts/bullet-chart/BulletChart.js
src/charts/bullet-chart/__snapshots__/BulletBars.test.js.snap
src/charts/bullet-chart/example/bullet.js
src/charts/bullet-chart/example/data.js
src/charts/bullet-chart/example/index.js
src/charts/bullet-chart/utils.js
src/index.js
style-guide/routes.js
webpack.static.config.js
yarn.lock

Adds a new Bullet Chart Component.
Demo:
http://president-randy-42828.netlify.com/docs/charts/bullet-chart
Due to fairly specific requirements i've added a new component rather than adapt the existing ColumnChart.
- Takes two data series. 
- Normalises data.
Showing normalised data

Bullet Chart

---

src/charts/bullet-chart/BulletBars.js
src/charts/bullet-chart/BulletChart.js
src/charts/bullet-chart/MirroredBulletChart.css
src/charts/bullet-chart/MirroredBulletChart.js
src/charts/bullet-chart/example/index.js
src/charts/bullet-chart/example/mirrored.js
src/index.js

Adds a new MIrrored Bullet Chart to complement the all ready added Bullet Chart
Preview
https://mirroredbulletchart.netlify.com/docs/charts/bullet-chart

feat(MirroredBulletChart): Adds mirrored bullet chart component

---

at_ids/README.md
at_ids/index.json
src/composites/login/Login.js

fix(Automated Testing): Adds ids to hook into components for ATs

---

src/charts/bar-chart/BarChart.css
src/charts/bar-chart/BarChart.js
src/charts/bar-chart/BarChartBars.js
src/charts/bar-chart/BarChartBenchmarkLine.js
src/charts/bar-chart/BarChartContext.js
src/charts/bars/Bar.css
src/charts/bars/Bar.js
src/charts/dot-plot/DotPlot.css
src/charts/vars.css

https://bar-chart-hover-improvements--axiom-rules.netlify.com/docs/charts/bar-chart

feat(BarChart): Hover behavior now more consistent with DotPlotChart giving more emphasis to the hovered data

---

src/components/icon/IconIndicator.css
src/components/icon/IconIndicator.js
src/components/icon/IconIndicator.test.js
src/components/icon/__snapshots__/IconIndicator.test.js.snap
src/components/icon/example/index.js
src/components/icon/example/indicator-secondary.js
src/components/progress/__snapshots__/Progress.test.js.snap

https://foreground-icon-indicator-colors--librarian-chimpanzee-34483.netlify.com/

feat(IconIndicator): add primary and secondary IconIndicator styles	

---

src/charts/bar-chart/BarChartContext.js
style-guide/components/ExampleConfig/ExampleConfig.js

Removes any interactions and displaying the label when percentage is exactly 0%.

fix(BarChart): Remove mouseover interaction on 0% value bars

---

src/components/form/TextInput.css
src/components/form/TextInput.js
src/components/form/TextInputIcon.js
src/components/form/TextInputIcon.test.js
src/components/form/__snapshots__/TextInput.test.js.snap
src/components/form/__snapshots__/TextInputIcon.test.js.snap
src/components/form/example/text-inputs-combined.js

https://feat-textinputicon-align-left--axiom-rules.netlify.com/docs/components/form

feat(TextInputIcon): Added optional align prop which can be set to left and defaults to right

---

src/components/context/ContextBox.css
src/components/context/ContextBox.js
src/components/context/ContextBox.test.js
src/components/context/__snapshots__/ContextBox.test.js.snap
src/components/context/__snapshots__/ContextMenu.test.js.snap
src/components/context/__snapshots__/ContextTip.test.js.snap
src/components/context/example/index.js

https://598322b0424ef2766dc9944d--librarian-chimpanzee-34483.netlify.com/docs/components/context

fix(ContextBox): Separate scrollable areas within a context popup

---

src/components/context/Context.css
src/components/context/ContextMenu.css
src/components/position/Position.js
src/components/position/_utils.js
src/components/position/example/index.js

* Added "onPositionChange" callback
* Added "flip" ordering options
* Fixed issue with flickering between two positions when repositioning
* Design change to removed the styling for left and right placements of the ContextMeny

Position features and fixes

---

README.md

Updated PR for #312 - doing things properly this time.

docs(readme): Add recommended base CSS a project should use

---

src/components/context/ContextMenuItem.test.js
src/components/context/__snapshots__/ContextMenuItem.test.js.snap
src/components/form/CheckBox.js
src/components/form/ChedioButtox.js
src/components/form/ChedioButtox.test.js
src/components/form/RadioButton.js
src/components/form/__snapshots__/CheckBox.test.js.snap
src/components/form/__snapshots__/CheckBoxGroup.test.js.snap
src/components/form/__snapshots__/ChedioButtox.test.js.snap
src/components/form/__snapshots__/ChedioButtoxGroup.test.js.snap
src/components/form/__snapshots__/RadioButton.test.js.snap
src/components/form/__snapshots__/RadioButtonGroup.test.js.snap
src/components/form/example/check-boxes.js
src/components/form/example/radio-buttons.js

https://chedio-buttox-title-fix--andyp-axiom.netlify.com/

fix(ChedioButtox): Moves title property to label element

---

src/components/context/Context.css
src/components/dialog/Dialog.css
src/components/notification/Notification.css
src/components/notification/Notification.js
src/components/notification/Notification.test.js
src/components/notification/Notifications.js
src/components/notification/__snapshots__/Notification.test.js.snap
src/components/notification/example/index.js
src/index.js
src/materials/colors.css
src/materials/layout.css
style-guide/components/ExampleConfig/utils.js
style-guide/containers/Labs.css
style-guide/routes.js
webpack.static.config.js

[Netlify Deploy](https://notifications--hhogg-axiom.netlify.com/)

feat(Notification): Added stackable floating Notification component

---

src/components/modal/Modal.css

Fixes unintended stacking context change from #353 affecting v25.12.1

fix(Modal): Contents of modal appearing as uninteractive

---

src/components/form/TextGroup.js
src/components/form/__snapshots__/TextInput.test.js.snap

... From [2f0753fc](https://github.com/BrandwatchLtd/axiom/commit/2f0753fc)

fix(TextGroup): Default spacing from 2f0753fc

---

package.json
scripts/component-docs.js
src/components/date-picker/DatePicker.css
src/components/date-picker/DatePicker.js
src/components/date-picker/DatePickerContext.js
src/components/date-picker/DatePickerControls.js
src/components/date-picker/DatePickerDay.js
src/components/date-picker/DatePickerHeaderControl.js
src/components/date-picker/DatePickerViewMonth.js
src/components/date-picker/example/index.js
src/components/date-picker/utils.js
src/index.js
style-guide/components/ExampleConfig/ComponentProp.js
style-guide/components/ExampleConfig/ComponentProps.js
style-guide/components/ExampleConfig/ExampleConfig.js
style-guide/components/ExampleConfig/TypeInstanceOf.js
style-guide/components/ExampleConfig/TypeInstanceOfDate.js
style-guide/components/ExampleConfig/utils.js
style-guide/routes.js
webpack.static.config.js
yarn.lock

feat(DatePicker): Added DatePicker component

---

src/components/platform/Console.css

fixes: e569f5ebb7cf6641cc927917b63780b1b3b14bcb

fix(Console): Typo in custom prop --color-context-text

---

src/components/context/Context.css
src/components/position/Position.css
src/components/position/Position.js
src/components/position/example/index.js

Popper offset to account for the margin that is applied around context when an arrow is used.

fix(Position): Positioning incorrect for start and end offsets

---

package.json
style-guide/components/Application/Application.js
style-guide/static.js
style-guide/utils/documentation-routes.js

I'm hoping this awkward base tag setup won't be a problem for much longer.

chore(Styleguide): Fixed basename setup for ghpages

---

src/composites/change-password/ChangePassword.js
src/composites/change-password/ChangePasswordForm.js
src/index.js
src/utils/listToSentence.js
src/utils/listToSentence.test.js
src/utils/locales/de/common.json
src/utils/locales/en/common.json
src/utils/locales/es/common.json
src/utils/locales/fr/common.json

https://librarian-chimpanzee-34483.netlify.com/docs/composites/change-password/

fix(ChangePassword): perform client-side validation

---

src/components/button/Button.css
src/components/button/Button.js
src/components/button/Button.test.js
src/components/button/__snapshots__/Button.test.js.snap
src/components/progress/Progress.js
src/components/progress/ProgressButton.css
src/components/progress/ProgressButton.js
src/components/progress/ProgressButton.test.js
src/components/progress/ProgressFinite.js
src/components/progress/ProgressInfinite.js
src/components/progress/RadialProgress.js
src/components/progress/__snapshots__/Progress.test.js.snap
src/components/progress/__snapshots__/ProgressButton.test.js.snap
src/components/progress/__snapshots__/ProgressFinite.test.js.snap
src/components/progress/__snapshots__/ProgressInfinite.test.js.snap
src/components/progress/__snapshots__/RadialProgress.test.js.snap
src/components/progress/example/button.js
src/components/progress/example/index.js
src/composites/change-password/ChangePassword.js
src/index.js

feat(Progress): Added ProgressButton component

---

src/components/table/Table.css

https://5a007a1d4c4b930e1ecb1004--axiom-rules.netlify.com/docs/components/table

fix(Table): Row separators are correct color and disappear on hover

---

src/components/table/Table.css
src/components/table/TableRow.js
src/components/table/example/index.js
src/materials/colors.css
src/materials/theme-dark.css
src/materials/theme-light.css

https://feat-table-row-hover-prop--axiom-rules.netlify.com/docs/components/table?state=%7B%22TableRow%22%3A%7B%22props%22%3A%7B%22hover%22%3Atrue%7D%7D%7D

feat(Table): Add hover prop to TableRow

---

CONTRIBUTING.md
src/components/button/Button.css
src/components/button/Button.js
src/materials/colors.css

This adds a caution button styling that's needed for modals in admin3 - the intention is for it to be used on destructive actions like delete etc.

feat(Button): Adding caution button

---

docs/create-react-app.md

Docs pointed at old css vars file.

docs(PostCSS): Update create create app docs to correct css var file

---

src/components/button/Button.css
src/components/button/Button.js
src/components/form/TextGroup.js
src/components/form/TextInput.css
src/components/form/TextInput.js
src/components/form/TextInput.test.js
src/components/form/TextInputButton.js
src/components/form/TextInputButton.test.js
src/components/form/__snapshots__/TextInput.test.js.snap
src/components/form/__snapshots__/TextInputButton.test.js.snap
src/components/form/example/text-input.js
src/index.js

https://librarian-chimpanzee-34483.netlify.com/

feat(TextInputButton): add a joined text input button

---

src/components/button/Button.css
src/components/button/Button.js
src/components/button/Button.test.js
src/components/button/__snapshots__/Button.test.js.snap
src/components/button/__snapshots__/ButtonGroup.test.js.snap
src/components/icon/IconButton.js
src/components/icon/__snapshots__/IconButton.test.js.snap
src/components/pagination/Pagination.js
src/components/pagination/PaginationButton.js
src/components/pagination/PaginationButton.test.js
src/components/pagination/__snapshots__/Pagination.test.js.snap
src/components/pagination/__snapshots__/PaginationButton.test.js.snap
src/components/progress/__snapshots__/ProgressButton.test.js.snap

BREAKING CHANGE:
Added `shape` property and removed `circular` and `stadium` from Button
```jsx
// Before
<Button circular={ SIZE }></Button>
<Button stadium={ SIZE }></Button>
// After
<Button shape="circle" size={ SIZE }></Button>
<Button shape="stadium" size={ SIZE }></Button>
```
BREAKING CHANGE:
`caution` value should now be set under the new  `color` prop
```jsx
// Before
<Button style="caution"></Button>
// After
<Button color="negative"></Button>
```

fix(Button): `shape`, `size`, `color` and `style` changes. 

---

src/charts/bar-chart/BarChart.css
src/charts/dot-plot/DotPlot.css
src/components/alert-dialog/AlertDialog.css
src/components/card/Card.css
src/components/context/Context.css
src/components/dialog/Dialog.css
src/components/form/CheckBox.css
src/components/form/ChedioButtox.css
src/components/form/Form.css
src/components/form/RadioButton.css
src/components/form/TextArea.css
src/components/form/TextGroup.css
src/components/form/TextInput.css
src/materials/colors.css
src/materials/colors/example/ColorSwatch.css
src/materials/theme-day.css
src/materials/theme-night.css

Fixes an issue where components were not using the correct theme colours when the theme was applied anywhere apart from the root element.

fix(Theme): Components using theme colours 

---

src/components/horizontal-rule/HorizontalRule.css
src/components/horizontal-rule/HorizontalRule.js
src/components/horizontal-rule/HorizontalRule.test.js
src/components/horizontal-rule/__snapshots__/HorizontalRule.test.js.snap

https://5a5f29c9df9953478cb1ba35--librarian-chimpanzee-34483.netlify.com/docs/components/horizontal-rule?state=%7B%22HorizontalRule%22%3A%7B%22props%22%3A%7B%22lineStyle%22%3A%22dotted%22%7D%7D%7D

fix(HorizontalRule): adds dotted horizontal rule style

---

src/components/editable/EditableLine.css
src/components/editable/EditableLine.js
src/components/editable/EditableTitle.css
src/components/editable/EditableTitle.js
src/components/editable/example/index.js
src/index.js
style-guide/map-documentation.js
style-guide/map-examples.js

[Netlify Link](https://editable--hhogg-axiom.netlify.com/docs/components/editable/)

feat(Editable): Added Editable and EditableTitle components

---

src/components/alert-bar/AlertBar.css
src/components/alert-bar/AlertBar.js
src/components/alert-bar/__snapshots__/AlertBar.test.js.snap
src/components/card/Card.css
src/components/card/CardCaption.js
src/components/label/Label.js
src/components/label/__snapshots__/Label.test.js.snap
src/components/label/__snapshots__/LabelGroup.test.js.snap
src/components/notification/Notification.css
src/components/notification/Notification.js
src/components/notification/__snapshots__/Notification.test.js.snap
src/materials/colors.css
src/materials/theme-day.css
src/materials/theme-night.css

Components using theme prop to quickly apply the correct theme, does not support pre-processing the custom properties which would sometimes leave the incorrect theme being applied.

fix(Theming): Removed components using themes under the hood

---

package.json
packages/axiom-charts/src/ChartGrid/ChartGrid.css
packages/axiom-charts/src/ChartGrid/ChartGrid.js
packages/axiom-charts/src/ChartLayout/ChartLabel.js
packages/axiom-charts/src/ChartLayout/ChartLayout.css
packages/axiom-charts/src/ChartLayout/ChartLayout.js
packages/axiom-charts/src/ChartLayout/ChartLayoutKey.js
packages/axiom-charts/src/ChartLayout/ChartLayoutLabels.js
packages/axiom-charts/src/ChartLayout/ChartLayoutTitle.js
packages/axiom-charts/src/ChartLayout/ChartLayoutVisual.js
packages/axiom-charts/src/Line/Line.js
packages/axiom-charts/src/LineChart/LineChart.css
packages/axiom-charts/src/LineChart/LineChart.js
packages/axiom-charts/src/index.js
postcss.config.js
scripts/publish_site.sh
site/components/Documentation/Resources/Charts.js
site/components/Documentation/Resources/Charts/BarChart.js
site/components/Documentation/Resources/Charts/Chart.js
site/components/Documentation/Resources/Charts/DotPlotChart.js
site/components/Documentation/Resources/Charts/DropdownContext.js
site/components/Documentation/Resources/Charts/LineChart.js
site/components/Documentation/Resources/Charts/TooltipContext.js
site/components/Documentation/Resources/Charts/WordCloud.js
webpack.static.config.js

_Required #470 to be merged first_

feat(LineChart): Added new LineChart component

---

packages/axiom-components/src/Card/Card.css

fix(Card): Added CardImage dotted separator

---

packages/babel-plugin-axiom-imports/src/resolve-import.js

In my project I use only a few axiom packages. This cause my build step to fail, because this plugin assumes that all axiom packages are installed. I added a try catch to prevent the plugin from failing.

Do not throw an error if not all axiom packages are used

---

packages/axiom-automation-testing/ids.json
packages/axiom-charts/package.json
packages/axiom-charts/src/BarChart/BarChartBars.js
packages/axiom-charts/src/DotPlotChart/DotPlotDots.js
packages/axiom-components/src/ColorPicker/ColorPicker.js
packages/axiom-components/src/DataPicker/DataPicker.js
packages/axiom-components/src/DataPicker/__snapshots__/DataPicker.test.js.snap
site/components/Documentation/Resources/Charts/BarChart.js

Added AT ids for DataPicker, ColorPicker, BarChart and DotPlotChart

Automation testing ids

---

.babelrc
packages/babel-plugin-axiom-imports/src/__snapshots__/babel-plugin-axiom-imports.test.js.snap
packages/babel-plugin-axiom-imports/src/babel-plugin-axiom-imports.js
packages/babel-plugin-axiom-imports/src/babel-plugin-axiom-imports.test.js
packages/babel-plugin-axiom-imports/test/all.js
packages/babel-plugin-axiom-imports/test/default.js
packages/babel-plugin-axiom-imports/test/direct.js
packages/babel-plugin-axiom-imports/test/scoped.js

Also fixes an issue where it was incorrectly transforming default parameters from an Axiom export.

Transform packages to use direct imports. 

---

packages/axiom-components/src/Base/Base.css
packages/axiom-components/src/Base/Base.js
packages/axiom-components/src/Base/Base.test.js
packages/axiom-components/src/Base/__snapshots__/Base.test.js.snap

This adds a new property called `container` to the Base component. When set to true it will set `position: relative;` on the element.

feat(Base): Add container property to Base component for relative positioning

---

packages/axiom-materials/src/colors.css
packages/axiom-materials/src/colors.js
site/components/Documentation/Resources/Materials/Colors.js

[Netlify Deploy](https://social-interaction-colours--hhogg-axiom.netlify.com/docs/packages/axiom-materials/colours)

feat(Colours): Added social interaction colours

---

packages/axiom-components/src/DataPicker/__snapshots__/DataPicker.test.js.snap
packages/axiom-components/src/Dropdown/Dropdown.js
packages/axiom-components/src/Dropdown/DropdownSource.js
packages/axiom-components/src/Dropdown/DropdownTarget.js
site/components/Documentation/Resources/Components/Dropdown.js

[Netlify Deploy](https://dropdown-open-on-focus--hhogg-axiom.netlify.com/docs/packages/axiom-components/dropdown)

fix(Dropdown): Open dropdown when DropdownTarget has focus

---

packages/axiom-charts/src/Line/LinePoint.js
packages/axiom-charts/src/LineChart/LineChart.js

This PR adds the index to the object that is passed in to the tooltip/dropdown of the LineChart.

Pass index of data to tooltip callback of the linechart

---

packages/axiom-components/src/Context/ContextMenuItem.js
packages/axiom-components/src/Context/ContextMenuItem.test.js
packages/axiom-components/src/Context/__snapshots__/ContextMenuItem.test.js.snap

feat(ContextMenuItem): Add icon prop to specify menu item icon

---

packages/axiom-components/src/Form/CheckBox.js
packages/axiom-components/src/Form/CheckBox.test.js
packages/axiom-components/src/Form/ChedioButtox.css
packages/axiom-components/src/Form/ChedioButtox.js
packages/axiom-components/src/Form/__snapshots__/CheckBox.test.js.snap

This basically adds a third state to the checkbox.
Livedemo: https://naughty-pasteur-6d413a.netlify.com/docs/packages/axiom-components/form/

feat(CheckBox): Added indeterminate property

---

packages/axiom-charts/src/BarChart/BarChart.js

fix(BarChart): Fix hover when BarChart has just single values

---

packages/axiom-charts/src/BarChart/BarChart.js

feat(BarChart): Add new prop isBenchmarkLineFadable

---

packages/axiom-charts/src/BarChart/BarChart.js
packages/axiom-charts/src/BarChart/BarChartBars.js
packages/axiom-charts/src/BarChart/CombinedBar.test.js
packages/axiom-charts/src/BarChart/__snapshots__/CombinedBar.test.js.snap
packages/axiom-charts/src/BarChart/utils.js
packages/axiom-charts/src/ChartTable/ChartTableLabel.js
packages/axiom-charts/src/ChartTable/ChartTableLabel.test.js
packages/axiom-charts/src/ChartTable/__snapshots__/ChartTableLabel.test.js.snap
site/components/Documentation/Resources/Charts/BarChart.js

Deployed here: https://5afaf2fcdd6a542479baef3f--naughty-pasteur-6d413a.netlify.com/docs/packages/axiom-charts/bar-chart
You have to activate `rowsConcealable `

feat(BarChart): Added rowsConcealable prop that activates show/hide controls for barchart rows

---

packages/axiom-charts/src/BarChart/BarChart.js
packages/axiom-charts/src/BarChart/BarChartBars.js
packages/axiom-charts/src/BarChart/CombinedBar.js
packages/axiom-charts/src/BarChart/CombinedBar.test.js
packages/axiom-charts/src/BarChart/__snapshots__/CombinedBar.test.js.snap
packages/axiom-charts/src/DotPlotChart/DotPlot.js
site/components/Documentation/Resources/Charts/BarChart.js

Add support for TooltipContext on DifferenceArea

---

CONTRIBUTING.md

I thought it might be helpful to share a few words about the Netlify workflow.

docs(contributing): Added section for Netlify deploys

---

packages/axiom-components/src/List/List.css

This reverts commit 262d494da521302278da7a4a41e3de94c5d8fce9.
Then takes an alternative approach using relative positioning.

fix(List): Tidies up the height of the vertical rule

---

packages/axiom-components/src/Tooltip/TooltipContext.js
site/components/Documentation/Resources/Components/Tooltip.js

https://5b39ff71dd28ef612e68618b--axiomwija.netlify.com/docs/packages/axiom-components/tooltip

docs(TooltipContext): add documented support for color prop

---

packages/axiom-components/src/AlertDialog/AlertDialog.js
packages/axiom-components/src/Dialog/Dialog.js
packages/axiom-components/src/Modal/Modal.js
packages/axiom-components/src/Modal/Modal.test.js
packages/axiom-components/src/Modal/__snapshots__/Modal.test.js.snap

This adds an event listener to the Modal component which calls the `onOverlayClick` function upon clicking the `esc` button.

SW-140 Close Modal when pressing Esc

---

packages/axiom-components/src/Slider/Slider.css
packages/axiom-components/src/Slider/Slider.js
packages/axiom-components/src/index.js
site/components/Documentation/Resources/Components.js
site/components/Documentation/Resources/Components/Slider.js

feat(Slider): Added slider component

---

packages/axiom-charts/src/DataPoint/DataPoint.js
packages/axiom-charts/src/DataPoint/DataPoints.css
packages/axiom-charts/src/RadarChart/RadarChart.css
packages/axiom-charts/src/RadarChart/RadarChart.js
packages/axiom-charts/src/RadarChart/RadarPoint.js
packages/axiom-charts/src/RadarChart/RadarPolygon.js
packages/axiom-charts/src/RadarChart/RadarXAxisLabel.js
packages/axiom-charts/src/RadarChart/RadarXAxisLine.js
packages/axiom-charts/src/RadarChart/RadarYAxisLabel.js
packages/axiom-charts/src/RadarChart/RadarYAxisLine.js
packages/axiom-charts/src/RadarChart/groupColorsByValue.js
packages/axiom-charts/src/RadarChart/groupColorsByValue.test.js
packages/axiom-charts/src/index.js
packages/axiom-components/src/Context/Context.css
packages/axiom-documentation-viewer/src/DocumentationShowCase.js
site/components/Documentation/Resources/Charts.js
site/components/Documentation/Resources/Charts/RadarChart.js
site/components/Documentation/Resources/Charts/chartData.js

[Netlify](https://radar-chart--hhogg-axiom.netlify.com/docs/packages/axiom-charts/radar-chart/)

Radar chart

---

packages/axiom-components/src/Card/Card.css

[NETLIFY](https://5b6ae9f6e39e7c6024c35ebb--andyp-axiom.netlify.com/)
**Before**
**After**

fix(Card): Fixes issue with image grids in Safari

---

packages/axiom-components/src/Dialog/Dialog.js
packages/axiom-components/src/Dialog/__snapshots__/Dialog.test.js.snap
packages/axiom-components/src/Modal/Modal.css
packages/axiom-components/src/Modal/Modal.js
packages/axiom-components/src/Modal/__snapshots__/Modal.test.js.snap

[Netlify](https://dialog-configurable-padding--hhogg-axiom.netlify.com/)

feat(Dialog): Configurable 'padding' prop

---

packages/axiom-components/src/Context/Context.css
packages/axiom-components/src/Context/Context.js
packages/axiom-components/src/Context/ContextContent.js
packages/axiom-components/src/Context/__snapshots__/Context.test.js.snap
packages/axiom-components/src/Dropdown/DropdownContent.js
packages/axiom-components/src/Dropdown/DropdownFooter.js
packages/axiom-components/src/Dropdown/DropdownHeader.js
packages/axiom-components/src/Position/Position.css
packages/axiom-components/src/Position/Position.js
packages/axiom-components/src/Slider/Slider.js
packages/axiom-components/src/Tip/Tip.css
packages/axiom-components/src/Tip/Tip.js
packages/axiom-components/src/Tip/__snapshots__/Tip.test.js.snap
packages/axiom-components/src/Tooltip/Tooltip.js
packages/axiom-components/src/Tooltip/TooltipContent.js
packages/axiom-materials/src/sizing.css
site/components/Documentation/Resources/Components/Tooltip.js

https://5b72963fc6aed67cf32b61df--axiomwija.netlify.com/docs/packages/axiom-components/tooltip/

AX-16 tooltip sizes

---

packages/axiom-components/src/Form/InputWrapper.js
packages/axiom-components/src/Form/TextArea.css
packages/axiom-components/src/Form/TextArea.js
packages/axiom-components/src/Form/TextInput.css
packages/axiom-components/src/Form/TextInput.js
packages/axiom-components/src/Form/__snapshots__/TextArea.test.js.snap
packages/axiom-components/src/Form/__snapshots__/TextInput.test.js.snap
packages/axiom-components/src/Select/__snapshots__/Select.test.js.snap
packages/axiom-components/src/UsageHint/UsageHint.js
site/components/Documentation/Resources/Components/Form.js

https://5b754700dd28ef26c0ced7d1--axiomwija.netlify.com/docs/packages/axiom-components/form

AX-31 progress indicators on form components

---

packages/axiom-components/src/Icon/Icon.js
packages/axiom-materials/src/icon_svgs/lock.svg
packages/axiom-materials/src/icons.js

feat(Icon): adds new lock icon

---

packages/axiom-components/src/Toggle/Toggle.css
packages/axiom-components/src/Toggle/Toggle.js
packages/axiom-components/src/Toggle/Toggle.test.js
packages/axiom-components/src/Toggle/__snapshots__/Toggle.test.js.snap

Adds `align` prop to the Toggle component, to align the label/switch `left`, `right`, or `full` (span)

feat(Toggle): Adds layout prop to Toggle component

---

packages/axiom-components/src/Grid/Grid.css
packages/axiom-components/src/Grid/Grid.js
packages/axiom-components/src/Grid/GridCell.js

This PR basically just adds a property to control the `flex-direction` property on a grid.

feat(Grid): Added direction property to control direction of grid

---

packages/axiom-materials/src/colors.css
packages/axiom-materials/src/colors.js

| Name | Hover | Default | Active
|---|---|---|---|
| Ground Control | ![#f03c15](https://placehold.it/15/AB6E46/000000?text=+) rgb(171,110,70) | ![#f03c15](https://placehold.it/15/9E6139/000000?text=+) rgb(158,97,57) | ![#f03c15](https://placehold.it/15/91552D/000000?text=+) rgb(145,85,45) |
| New Horizon | ![#f03c15](https://placehold.it/15/FEC731/000000?text=+) rgb(254,199,49) | ![#f03c15](https://placehold.it/15/FFBE0A/000000?text=+) rgb(255,190,10) | ![#f03c15](https://placehold.it/15/F2B200/000000?text=+) rgb(242,178,0) |
| Giant Leap | ![#f03c15](https://placehold.it/15/66DBF2/000000?text=+) rgb(102,219,242) | ![#f03c15](https://placehold.it/15/55CDE6/000000?text=+) rgb(85,205,230) | ![#f03c15](https://placehold.it/15/45C0D9/000000?text=+) rgb(69,192,217) |
| Extraterrestrial | …

feat(Colors): Update values of existing colors

---

site/components/Documentation/Resources/PackagesTable/PackageRow.js

chore(doc): Fix GitHub link

---

packages/axiom-components/src/Base/Base.js
packages/axiom-components/src/Typography/Text.css

This PR adds ui-accent colour support for textColor to Base component

feat(Base): Added color ui-accent as textColor

---

packages/axiom-components/src/Animation/Animation.css
packages/axiom-components/src/Animation/Animation.js
packages/axiom-components/src/index.js
site/components/Documentation/Resources/Components.js
site/components/Documentation/Resources/Components/Animation.js

https://nt-animations--axiomwija.netlify.com/docs/packages/axiom-components/animation

WIP - Animation

---

packages/axiom-automation-testing/README.md
packages/axiom-charts/README.md
packages/axiom-components/README.md
packages/axiom-composites/README.md
packages/axiom-documentation-loader/README.md
packages/axiom-documentation-viewer/README.md
packages/axiom-formatting/README.md
packages/axiom-localization/README.md
packages/axiom-materials/README.md
packages/axiom-utils/README.md
packages/babel-plugin-axiom-imports/README.md
packages/babel-plugin-transform-svg-axiom/README.md
packages/eslint-config-axiom/README.md
packages/stylelint-config-axiom/README.md

Update README for all axiom packages.

AX-111 update readme for every package

---

PATTERNS.md

Adding this here for now until we have a section in the documentation, where we can stick it in.
There has been no feedback on this yet, so happy to hear some here as well.

chore(docs): patterns for large data sets

---

packages/axiom-components/src/Form/TextInputIcon.js
packages/axiom-components/src/Form/TextInputIcon.test.js
packages/axiom-components/src/Form/__snapshots__/TextInputIcon.test.js.snap

Add support for changing the icon color for text input icon in axiom. 
Netlify Link: https://deploy-preview-716--serene-shannon-8198f2.netlify.com/

feat(TextInputIcon): Allow setting iconColor for TextInputIcon

---

packages/axiom-materials/src/colors.css
packages/axiom-materials/src/colors.js

fix(color): Fix active/default/hover Warning color

---

packages/axiom-components/src/Icon/Icon.js
packages/axiom-materials/src/icon_svgs/filter.svg
packages/axiom-materials/src/icon_svgs/growth.svg
packages/axiom-materials/src/icons.js

https://agitated-mcnulty-e82f96.netlify.com/docs/packages/axiom-components/icon

Icons: Add growth. Updating Filter.

---

.travis.yml
CONTRIBUTING.md
package.json
scripts/build_packages.sh
scripts/publish_packages.sh
scripts/publish_packages_ci.sh

The build dist is currently broken because a build step was missed before the last publish, this will ensure that happens. I think.
Also, is there a time frame on auto publishing from CI?

fix: builds flags before publishing

---

packages/axiom-components/src/Form/ChedioButtox.css

This updates the design of radio and checkboxes.

feat(Checkbox, RadioButton): change style of selected and active

---

scripts/publish_site.sh

Previously it would remove the entire bucket but this would remove additional directories uploaded by other Axiom projects.

docs: Site publishing is more selective and targets specific directories

---

packages/axiom-charts/package.json
packages/axiom-composites/package.json
yarn.lock

We are using two versions of React. 1 > 2.

chore(React): Make use of react versions consistent 

---

packages/axiom-components/src/Form/TextInput.test.js
packages/axiom-components/src/Form/TextInputIcon.js
packages/axiom-components/src/Form/TextInputIcon.test.js
packages/axiom-components/src/Form/__snapshots__/TextInput.test.js.snap
packages/axiom-components/src/Form/__snapshots__/TextInputIcon.test.js.snap

Adds the ability to specify a tooltip for TextInputIcon.
Note that as per the commit message, I fleshed out some tests for TextInput as well

Textinput icon tooltip

---

packages/axiom-components/src/DurationPicker/__snapshots__/DurationPicker.test.js.snap
packages/axiom-components/src/Form/InputWrapper.css
packages/axiom-components/src/Form/InputWrapper.js
packages/axiom-components/src/Form/TextInput.js
site/components/Documentation/Resources/Components/Form.js

Needed for [this](https://gallery.io/projects/MCHbtQVoQ2HCZfdKS5mfp1QP/files/MCEJu8Y2hyDScaRzadWt9gKBy3v2dRcOs2A) design seems like a pretty standard feature.
Netlify [Preview](https://deploy-preview-752--serene-shannon-8198f2.netlify.com/docs/packages/axiom-components/form)

feat(TextInput): Adds ability to display form labels inline

---

packages/axiom-components/src/DatePicker/DatePicker.js
packages/axiom-components/src/DatePicker/DatePickerSelection.js
packages/axiom-components/src/index.js
site/components/Documentation/Resources/Components/DatePicker.js

Exporting DatePickerSelection so that the DatePicker can be used without a Dropdown.

feat(DatePicker): Exporting DatePickerSelection

---

packages/axiom-components/src/Icon/Icon.js
packages/axiom-materials/src/icon_svgs/user.svg
packages/axiom-materials/src/icons.js

feat(Icon): Adding user icon

---

packages/axiom-materials/src/colors.css

they can now be used to construct an RGBA with opacity variables

chore(axiom-materials): add rgb variable for all colors

---

packages/axiom-materials/src/colors.css
packages/axiom-materials/src/colors.js
site/components/Documentation/Resources/Materials/Colors.js

Update Facebook
Add 4chan
Add Reddit
Add Tumble
Add VK
Add YouTube

feat(color): update social colors

---

packages/axiom-components/src/Button/Button.js

Adds className prop to Button.

feat(Button): add className to Button

---

packages/axiom-materials/src/colors.css
packages/axiom-materials/src/colors.js
site/components/Documentation/Resources/Materials/Colors.js

feat(colors): Add Brand color set

---

packages/axiom-components/src/Icon/Icon.js
packages/axiom-materials/src/icon_svgs/settings.svg
packages/axiom-materials/src/icons.js

feat(Icon): Adding settings icon

---

packages/axiom-components/src/Chip/Chip.css

Fixes minor typo / invalid CSS

fix(Chip): remove dash before var

---

packages/axiom-charts/src/Bar/Bar.css
packages/axiom-charts/src/Bar/Bar.js

Add missing colors to Bars used in Bar Chart in order to fix the benchmark component.

Pint 770 add colors to bars

---

packages/axiom-components/src/Icon/Icon.js
packages/axiom-materials/src/icon_svgs/filter-line.svg
packages/axiom-materials/src/icons.js

feat(Icon): adding filter-line icon

---

packages/axiom-components/src/Icon/Icon.js
packages/axiom-materials/src/icon_svgs/download.svg
packages/axiom-materials/src/icons.js

feat(Icon): Add download icon

---

packages/axiom-components/src/Table/Table.js
packages/axiom-components/src/Table/TableBody.js
packages/axiom-components/src/Table/TableCell.js
packages/axiom-components/src/Table/TableHeader.js
packages/axiom-components/src/Table/TableHeaderLabel.js
packages/axiom-components/src/Table/TableRow.js

Adds Classname prop to all Table components.

feat(Table): Allow classname to be passed to Table Components

---

scripts/build_packages.sh

Glob misses some files when not in a string. Think its a postcss cli bug 🤷

fix: PostCSS was not being run on build files.

---

packages/axiom-components/src/AlertIcon/AlertIcon.js
packages/axiom-components/src/Typography/Link.js

Add classnames to AlertIcon & Link

feat: 🎸 Add classNames to AlertIcon & Link

---

packages/axiom-components/src/Platform/Canvas.js
packages/axiom-components/src/Platform/Console.js
packages/axiom-components/src/Platform/ConsoleContext.js
packages/axiom-components/src/Platform/ConsoleHeader.js
packages/axiom-components/src/Platform/Platform.js
packages/axiom-components/src/Platform/Platform.stories.js
packages/axiom-components/src/Platform/PlatformContext.js

Removes legacy Context from `Platform` and children components also took the opportunity to add an example story.

Platform context

---

packages/axiom-components/src/Icon/Icon.js
packages/axiom-materials/src/icon_svgs/pause.svg
packages/axiom-materials/src/icons.js

chore: add pause icon

---

packages/axiom-components/src/Tooltip/Tooltip.js
packages/axiom-components/src/Tooltip/Tooltip.stories.js
packages/axiom-components/src/Tooltip/TooltipTarget.js

Added Tooltip to Storybook.
Removed React's Legacy Context API from Tooltip.

Tooltip add Storybook / remove context

---

packages/axiomDocs.stories.mdx

Mostly just triggering a build.

docs: ✏️ Update project description

---

packages/axiom-components/src/ColorPicker/ColorPicker.js
packages/axiom-components/src/ColorPicker/ColorPicker.stories.js

This adds the option to see an empty colour in the colour picker allowing the user to clear their previously selected option.

feat(ColorPicker): add withEmpty prop for clearing selection

---

.storybook/static_assets/flags/gb.svg
packages/axiom-components/src/DurationPicker/DurationPicker.stories.js
packages/axiom-components/src/Flag/Flag.stories.js
packages/axiom-components/src/Reveal/Reveal.stories.js
packages/axiom-components/src/Select/Select.stories.js
packages/axiom-components/src/Separator/Separator.stories.js
packages/axiom-components/src/Transition/Transition.stories.css
packages/axiom-components/src/Transition/Transition.stories.js

Adding the last few components to bring Storybook coverage above that of the current docs.
Components

Last few components

---

.storybook/main.js
.storybook/preview.js
README.md
package.json
packages/axiom-components/src/Button/Button.stories.js
packages/axiom-components/src/Dropdown/Dropdown.stories.js
packages/axiom-components/src/Dropdown/Dropdown.stories.mdx
yarn.lock

This reverts commit b78fbf24836c37944a775378c1289d2b4dd3fa13.

Revert "docs: ✏️ update button example to include variant"

---

packages/axiom-components/src/AlertDialog/AlertDialog.stories.js
packages/axiom-components/src/Animation/Animation.js
packages/axiom-components/src/Animation/Animation.stories.js
packages/axiom-components/src/Base/Base.js
packages/axiom-components/src/Base/Base.stories.js
packages/axiom-components/src/Button/Button.stories.js
packages/axiom-components/src/Card/Card.js
packages/axiom-components/src/Cloak/Cloak.js
packages/axiom-components/src/Cloak/Cloak.stories.js
packages/axiom-components/src/ColorPicker/ColorPicker.stories.js
packages/axiom-components/src/DatePicker/DatePicker.stories.js
packages/axiom-components/src/Dialog/Dialog.stories.js
packages/axiom-components/src/Dropdown/Dropdown.stories.css
packages/axiom-components/src/Dropdown/Dropdown.stories.js
packages/axiom-components/src/Dropdown/Dropdown.stories.mdx

A-D
A few small tweeks and improvements to stories.

More sb docs

---

.github/workflows/build.yml
packages/axiom-charts/src/BarChart/__snapshots__/CombinedBar.test.js.snap
packages/axiom-components/src/Dropdown/DropdownMenuItem.test.js
packages/axiom-components/src/Modal/__snapshots__/Modal.test.js.snap
yarn.lock

I'm not sure why but this fixes the broken routing in sb static builds

chore: 🤖 regenerate yarn lock file to remove sb routing issue

---

packages/axiom-components/src/Dropdown/Dropdown.stories.js
packages/axiom-components/src/Dropdown/Dropdown.stories.mdx

This is a workaround for this issue
https://github.com/storybookjs/storybook/issues/9583 we should be able
to revert this commit once that issues if fixed. This soultion is very,
very, very ugly

docs: ✏️ Dropdown, show stories src in mdx

---

.storybook/manager.js
.storybook/preview.js
package.json
packages/axiom-components/src/AlertBar/AlertBar.stories.js
packages/axiom-components/src/AlertCard/AlertCard.stories.js
packages/axiom-components/src/AlertDialog/AlertDialog.stories.js
packages/axiom-components/src/AlertIcon/AlertIcon.stories.js
packages/axiom-components/src/Animation/Animation.stories.js
packages/axiom-components/src/Avatar/Avatar.stories.js
packages/axiom-components/src/Button/Button.stories.js
packages/axiom-components/src/Icon/IconButton.stories.js
packages/colors-and-themes.stories.mdx

General docs site tweaks.
- Add Link to axiom materials colors/themes
- Show canvas tab in production
- Add controls to more components

docs: ✏️ Link to axiom materials colors/themes

---

package.json
packages/axiom-components/src/Lozenge/Lozenge.css
packages/axiom-components/src/Lozenge/Lozenge.js
packages/axiom-components/src/Lozenge/Lozenge.stories.js
packages/axiom-components/src/Lozenge/Lozenge.test.js
packages/axiom-components/src/Lozenge/LozengeGroup.js
packages/axiom-components/src/Lozenge/StatusIndicator.js
packages/axiom-components/src/Progress/ProgressInfinite.js
packages/axiom-components/src/index.js
yarn.lock

* Adds new Lozenge component
* Adds react-testing-libary

feat(Lozenge): Adds new Lozenge component

---

.github/workflows/build.yml
.storybook/axiomTheme.js

Roboto not working in safari not sure why yet

docs: ✏️ fallback to Helvetica font in docs

---

packages/axiom-components/src/Card/Card.js
packages/axiom-components/src/Card/Card.stories.js
packages/axiom-components/src/Card/CardList.js

chore: 🤖 Card & CardList remove legacy context api

---

packages/axiom-materials/src/typography.js

closes #944
Copy of this file
https://github.com/BrandwatchLtd/axiom-react/blob/master/packages/axiom-materials/src/typography.css

feat: 🎸 Provide a js export for typography values

---

packages/axiom-components/src/DatePicker/DatePickerControls.js

Convert to function component to make use of useContext

refactor: 💡 Remove legacy context API from DatePickerControls

---

packages/axiom-components/src/Dialog/Dialog.js
packages/axiom-components/src/Dialog/DialogHeader.js

Convert to function component whilst here

refactor: 💡 Remove legacy context API from Dialog/ DialogHeader

---

packages/axiom-components/src/Context/Context.css
packages/axiom-components/src/Context/Context.js
packages/axiom-components/src/Context/Context.stories.js
packages/axiom-components/src/Context/__snapshots__/Context.test.js.snap
packages/axiom-components/src/Position/Position.stories.js
packages/axiom-components/src/Tooltip/Tooltip.js
packages/axiom-components/src/Tooltip/Tooltip.stories.js

docs: ✏️ Context Docs

---

packages/axiom-components/src/AnimatedLogo/AnimatedLogo.js
packages/axiom-components/src/AnimatedLogo/logos/DataLogo.js

feat(axiom-components): add data logo to animated logo component

---

packages/axiom-components/src/Chip/Chip.css
packages/axiom-components/src/Chip/Chip.js
packages/axiom-components/src/Chip/Chip.stories.js

feat(Chip): updating design

---

.eslintignore
packages/axiom-components/src/index.d.ts

Update the index.d.ts file to include more up-to-date types

chore: update types

---

packages/axiom-components/src/Icon/Icon.js
packages/axiom-components/src/Icon/iconNames.js
packages/axiom-materials/src/icon_svgs/copy.svg
packages/axiom-materials/src/icons.js

feat: add copy icon to axiom-materials/components
